# coding=utf-8
# Copyright 2022 the HuggingFace Datasets Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from collections import OrderedDict


IMAGENET2012_CLASSES = OrderedDict(
    {
        "0": "tench, Tinca tinca",
        "1": "goldfish, Carassius auratus",
        "2": "great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias",
        "3": "tiger shark, Galeocerdo cuvieri",
        "4": "hammerhead, hammerhead shark",
        "5": "electric ray, crampfish, numbfish, torpedo",
        "6": "stingray",
        "7": "cock",
        "8": "hen",
        "9": "ostrich, Struthio camelus",
        "10": "brambling, Fringilla montifringilla",
        "11": "goldfinch, Carduelis carduelis",
        "12": "house finch, linnet, Carpodacus mexicanus",
        "13": "junco, snowbird",
        "14": "indigo bunting, indigo finch, indigo bird, Passerina cyanea",
        "15": "robin, American robin, Turdus migratorius",
        "16": "bulbul",
        "17": "jay",
        "18": "magpie",
        "19": "chickadee",
        "20": "water ouzel, dipper",
        "21": "kite",
        "22": "bald eagle, American eagle, Haliaeetus leucocephalus",
        "23": "vulture",
        "24": "great grey owl, great gray owl, Strix nebulosa",
        "25": "European fire salamander, Salamandra salamandra",
        "26": "common newt, Triturus vulgaris",
        "27": "eft",
        "28": "spotted salamander, Ambystoma maculatum",
        "29": "axolotl, mud puppy, Ambystoma mexicanum",
        "30": "bullfrog, Rana catesbeiana",
        "31": "tree frog, tree-frog",
        "32": "tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui",
        "33": "loggerhead, loggerhead turtle, Caretta caretta",
        "34": "leatherback turtle, leatherback, leathery turtle, Dermochelys coriacea",
        "35": "mud turtle",
        "36": "terrapin",
        "37": "box turtle, box tortoise",
        "38": "banded gecko",
        "39": "common iguana, iguana, Iguana iguana",
        "40": "American chameleon, anole, Anolis carolinensis",
        "41": "whiptail, whiptail lizard",
        "42": "agama",
        "43": "frilled lizard, Chlamydosaurus kingi",
        "44": "alligator lizard",
        "45": "Gila monster, Heloderma suspectum",
        "46": "green lizard, Lacerta viridis",
        "47": "African chameleon, Chamaeleo chamaeleon",
        "48": "Komodo dragon, Komodo lizard, dragon lizard, giant lizard, Varanus komodoensis",
        "49": "African crocodile, Nile crocodile, Crocodylus niloticus",
        "50": "American alligator, Alligator mississipiensis",
        "51": "triceratops",
        "52": "thunder snake, worm snake, Carphophis amoenus",
        "53": "ringneck snake, ring-necked snake, ring snake",
        "54": "hognose snake, puff adder, sand viper",
        "55": "green snake, grass snake",
        "56": "king snake, kingsnake",
        "57": "garter snake, grass snake",
        "58": "water snake",
        "59": "vine snake",
        "60": "night snake, Hypsiglena torquata",
        "61": "boa constrictor, Constrictor constrictor",
        "62": "rock python, rock snake, Python sebae",
        "63": "Indian cobra, Naja naja",
        "64": "green mamba",
        "65": "sea snake",
        "66": "horned viper, cerastes, sand viper, horned asp, Cerastes cornutus",
        "67": "diamondback, diamondback rattlesnake, Crotalus adamanteus",
        "68": "sidewinder, horned rattlesnake, Crotalus cerastes",
        "69": "trilobite",
        "70": "harvestman, daddy longlegs, Phalangium opilio",
        "71": "scorpion",
        "72": "black and gold garden spider, Argiope aurantia",
        "73": "barn spider, Araneus cavaticus",
        "74": "garden spider, Aranea diademata",
        "75": "black widow, Latrodectus mactans",
        "76": "tarantula",
        "77": "wolf spider, hunting spider",
        "78": "tick",
        "79": "centipede",
        "80": "black grouse",
        "81": "ptarmigan",
        "82": "ruffed grouse, partridge, Bonasa umbellus",
        "83": "prairie chicken, prairie grouse, prairie fowl",
        "84": "peacock",
        "85": "quail",
        "86": "partridge",
        "87": "African grey, African gray, Psittacus erithacus",
        "88": "macaw",
        "89": "sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita",
        "90": "lorikeet",
        "91": "coucal",
        "92": "bee eater",
        "93": "hornbill",
        "94": "hummingbird",
        "95": "jacamar",
        "96": "toucan",
        "97": "drake",
        "98": "red-breasted merganser, Mergus serrator",
        "99": "goose",
        "100": "black swan, Cygnus atratus",
        "101": "tusker",
        "102": "echidna, spiny anteater, anteater",
        "103": "platypus, duckbill, duckbilled platypus, duck-billed platypus, Ornithorhynchus anatinus",
        "104": "wallaby, brush kangaroo",
        "105": "koala, koala bear, kangaroo bear, native bear, Phascolarctos cinereus",
        "106": "wombat",
        "107": "jellyfish",
        "108": "sea anemone, anemone",
        "109": "brain coral",
        "110": "flatworm, platyhelminth",
        "111": "nematode, nematode worm, roundworm",
        "112": "conch",
        "113": "snail",
        "114": "slug",
        "115": "sea slug, nudibranch",
        "116": "chiton, coat-of-mail shell, sea cradle, polyplacophore",
        "117": "chambered nautilus, pearly nautilus, nautilus",
        "118": "Dungeness crab, Cancer magister",
        "119": "rock crab, Cancer irroratus",
        "120": "fiddler crab",
        "121": "king crab, Alaska crab, Alaskan king crab, Alaska king crab, Paralithodes camtschatica",
        "122": "American lobster, Northern lobster, Maine lobster, Homarus americanus",
        "123": "spiny lobster, langouste, rock lobster, crawfish, crayfish, sea crawfish",
        "124": "crayfish, crawfish, crawdad, crawdaddy",
        "125": "hermit crab",
        "126": "isopod",
        "127": "white stork, Ciconia ciconia",
        "128": "black stork, Ciconia nigra",
        "129": "spoonbill",
        "130": "flamingo",
        "131": "little blue heron, Egretta caerulea",
        "132": "American egret, great white heron, Egretta albus",
        "133": "bittern",
        "134": "crane",
        "135": "limpkin, Aramus pictus",
        "136": "European gallinule, Porphyrio porphyrio",
        "137": "American coot, marsh hen, mud hen, water hen, Fulica americana",
        "138": "bustard",
        "139": "ruddy turnstone, Arenaria interpres",
        "140": "red-backed sandpiper, dunlin, Erolia alpina",
        "141": "redshank, Tringa totanus",
        "142": "dowitcher",
        "143": "oystercatcher, oyster catcher",
        "144": "pelican",
        "145": "king penguin, Aptenodytes patagonica",
        "146": "albatross, mollymawk",
        "147": "grey whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus",
        "148": "killer whale, killer, orca, grampus, sea wolf, Orcinus orca",
        "149": "dugong, Dugong dugon",
        "150": "sea lion",
        "151": "Chihuahua",
        "152": "Japanese spaniel",
        "153": "Maltese dog, Maltese terrier, Maltese",
        "154": "Pekinese, Pekingese, Peke",
        "155": "Shih-Tzu",
        "156": "Blenheim spaniel",
        "157": "papillon",
        "158": "toy terrier",
        "159": "Rhodesian ridgeback",
        "160": "Afghan hound, Afghan",
        "161": "basset, basset hound",
        "162": "beagle",
        "163": "bloodhound, sleuthhound",
        "164": "bluetick",
        "165": "black-and-tan coonhound",
        "166": "Walker hound, Walker foxhound",
        "167": "English foxhound",
        "168": "redbone",
        "169": "borzoi, Russian wolfhound",
        "170": "Irish wolfhound",
        "171": "Italian greyhound",
        "172": "whippet",
        "173": "Ibizan hound, Ibizan Podenco",
        "174": "Norwegian elkhound, elkhound",
        "175": "otterhound, otter hound",
        "176": "Saluki, gazelle hound",
        "177": "Scottish deerhound, deerhound",
        "178": "Weimaraner",
        "179": "Staffordshire bullterrier, Staffordshire bull terrier",
        "180": "American Staffordshire terrier, Staffordshire terrier, American pit bull terrier, pit bull terrier",
        "181": "Bedlington terrier",
        "182": "Border terrier",
        "183": "Kerry blue terrier",
        "184": "Irish terrier",
        "185": "Norfolk terrier",
        "186": "Norwich terrier",
        "187": "Yorkshire terrier",
        "188": "wire-haired fox terrier",
        "189": "Lakeland terrier",
        "190": "Sealyham terrier, Sealyham",
        "191": "Airedale, Airedale terrier",
        "192": "cairn, cairn terrier",
        "193": "Australian terrier",
        "194": "Dandie Dinmont, Dandie Dinmont terrier",
        "195": "Boston bull, Boston terrier",
        "196": "miniature schnauzer",
        "197": "giant schnauzer",
        "198": "standard schnauzer",
        "199": "Scotch terrier, Scottish terrier, Scottie",
        "200": "Tibetan terrier, chrysanthemum dog",
        "201": "silky terrier, Sydney silky",
        "202": "soft-coated wheaten terrier",
        "203": "West Highland white terrier",
        "204": "Lhasa, Lhasa apso",
        "205": "flat-coated retriever",
        "206": "curly-coated retriever",
        "207": "golden retriever",
        "208": "Labrador retriever",
        "209": "Chesapeake Bay retriever",
        "210": "German short-haired pointer",
        "211": "vizsla, Hungarian pointer",
        "212": "English setter",
        "213": "Irish setter, red setter",
        "214": "Gordon setter",
        "215": "Brittany spaniel",
        "216": "clumber, clumber spaniel",
        "217": "English springer, English springer spaniel",
        "218": "Welsh springer spaniel",
        "219": "cocker spaniel, English cocker spaniel, cocker",
        "220": "Sussex spaniel",
        "221": "Irish water spaniel",
        "222": "kuvasz",
        "223": "schipperke",
        "224": "groenendael",
        "225": "malinois",
        "226": "briard",
        "227": "kelpie",
        "228": "komondor",
        "229": "Old English sheepdog, bobtail",
        "230": "Shetland sheepdog, Shetland sheep dog, Shetland",
        "231": "collie",
        "232": "Border collie",
        "233": "Bouvier des Flandres, Bouviers des Flandres",
        "234": "Rottweiler",
        "235": "German shepherd, German shepherd dog, German police dog, alsatian",
        "236": "Doberman, Doberman pinscher",
        "237": "miniature pinscher",
        "238": "Greater Swiss Mountain dog",
        "239": "Bernese mountain dog",
        "240": "Appenzeller",
        "241": "EntleBucher",
        "242": "boxer",
        "243": "bull mastiff",
        "244": "Tibetan mastiff",
        "245": "French bulldog",
        "246": "Great Dane",
        "247": "Saint Bernard, St Bernard",
        "248": "Eskimo dog, husky",
        "249": "malamute, malemute, Alaskan malamute",
        "250": "Siberian husky",
        "251": "dalmatian, coach dog, carriage dog",
        "252": "affenpinscher, monkey pinscher, monkey dog",
        "253": "basenji",
        "254": "pug, pug-dog",
        "255": "Leonberg",
        "256": "Newfoundland, Newfoundland dog",
        "257": "Great Pyrenees",
        "258": "Samoyed, Samoyede",
        "259": "Pomeranian",
        "260": "chow, chow chow",
        "261": "keeshond",
        "262": "Brabancon griffon",
        "263": "Pembroke, Pembroke Welsh corgi",
        "264": "Cardigan, Cardigan Welsh corgi",
        "265": "toy poodle",
        "266": "miniature poodle",
        "267": "standard poodle",
        "268": "Mexican hairless",
        "269": "timber wolf, grey wolf, gray wolf, Canis lupus",
        "270": "white wolf, Arctic wolf, Canis lupus tundrarum",
        "271": "red wolf, maned wolf, Canis rufus, Canis niger",
        "272": "coyote, prairie wolf, brush wolf, Canis latrans",
        "273": "dingo, warrigal, warragal, Canis dingo",
        "274": "dhole, Cuon alpinus",
        "275": "African hunting dog, hyena dog, Cape hunting dog, Lycaon pictus",
        "276": "hyena, hyaena",
        "277": "red fox, Vulpes vulpes",
        "278": "kit fox, Vulpes macrotis",
        "279": "Arctic fox, white fox, Alopex lagopus",
        "280": "grey fox, gray fox, Urocyon cinereoargenteus",
        "281": "tabby, tabby cat",
        "282": "tiger cat",
        "283": "Persian cat",
        "284": "Siamese cat, Siamese",
        "285": "Egyptian cat",
        "286": "cougar, puma, catamount, mountain lion, painter, panther, Felis concolor",
        "287": "lynx, catamount",
        "288": "leopard, Panthera pardus",
        "289": "snow leopard, ounce, Panthera uncia",
        "290": "jaguar, panther, Panthera onca, Felis onca",
        "291": "lion, king of beasts, Panthera leo",
        "292": "tiger, Panthera tigris",
        "293": "cheetah, chetah, Acinonyx jubatus",
        "294": "brown bear, bruin, Ursus arctos",
        "295": "American black bear, black bear, Ursus americanus, Euarctos americanus",
        "296": "ice bear, polar bear, Ursus Maritimus, Thalarctos maritimus",
        "297": "sloth bear, Melursus ursinus, Ursus ursinus",
        "298": "mongoose",
        "299": "meerkat, mierkat",
        "300": "tiger beetle",
        "301": "ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle",
        "302": "ground beetle, carabid beetle",
        "303": "long-horned beetle, longicorn, longicorn beetle",
        "304": "leaf beetle, chrysomelid",
        "305": "dung beetle",
        "306": "rhinoceros beetle",
        "307": "weevil",
        "308": "fly",
        "309": "bee",
        "310": "ant, emmet, pismire",
        "311": "grasshopper, hopper",
        "312": "cricket",
        "313": "walking stick, walkingstick, stick insect",
        "314": "cockroach, roach",
        "315": "mantis, mantid",
        "316": "cicada, cicala",
        "317": "leafhopper",
        "318": "lacewing, lacewing fly",
        "319": "dragonfly, darning needle, devil's darning needle, sewing needle, snake feeder, snake doctor, mosquito hawk, skeeter hawk",
        "320": "damselfly",
        "321": "admiral",
        "322": "ringlet, ringlet butterfly",
        "323": "monarch, monarch butterfly, milkweed butterfly, Danaus plexippus",
        "324": "cabbage butterfly",
        "325": "sulphur butterfly, sulfur butterfly",
        "326": "lycaenid, lycaenid butterfly",
        "327": "starfish, sea star",
        "328": "sea urchin",
        "329": "sea cucumber, holothurian",
        "330": "wood rabbit, cottontail, cottontail rabbit",
        "331": "hare",
        "332": "Angora, Angora rabbit",
        "333": "hamster",
        "334": "porcupine, hedgehog",
        "335": "fox squirrel, eastern fox squirrel, Sciurus niger",
        "336": "marmot",
        "337": "beaver",
        "338": "guinea pig, Cavia cobaya",
        "339": "sorrel",
        "340": "zebra",
        "341": "hog, pig, grunter, squealer, Sus scrofa",
        "342": "wild boar, boar, Sus scrofa",
        "343": "warthog",
        "344": "hippopotamus, hippo, river horse, Hippopotamus amphibius",
        "345": "ox",
        "346": "water buffalo, water ox, Asiatic buffalo, Bubalus bubalis",
        "347": "bison",
        "348": "ram, tup",
        "349": "bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky Mountain sheep, Ovis canadensis",
        "350": "ibex, Capra ibex",
        "351": "hartebeest",
        "352": "impala, Aepyceros melampus",
        "353": "gazelle",
        "354": "Arabian camel, dromedary, Camelus dromedarius",
        "355": "llama",
        "356": "weasel",
        "357": "mink",
        "358": "polecat, fitch, foulmart, foumart, Mustela putorius",
        "359": "black-footed ferret, ferret, Mustela nigripes",
        "360": "otter",
        "361": "skunk, polecat, wood pussy",
        "362": "badger",
        "363": "armadillo",
        "364": "three-toed sloth, ai, Bradypus tridactylus",
        "365": "orangutan, orang, orangutang, Pongo pygmaeus",
        "366": "gorilla, Gorilla gorilla",
        "367": "chimpanzee, chimp, Pan troglodytes",
        "368": "gibbon, Hylobates lar",
        "369": "siamang, Hylobates syndactylus, Symphalangus syndactylus",
        "370": "guenon, guenon monkey",
        "371": "patas, hussar monkey, Erythrocebus patas",
        "372": "baboon",
        "373": "macaque",
        "374": "langur",
        "375": "colobus, colobus monkey",
        "376": "proboscis monkey, Nasalis larvatus",
        "377": "marmoset",
        "378": "capuchin, ringtail, Cebus capucinus",
        "379": "howler monkey, howler",
        "380": "titi, titi monkey",
        "381": "spider monkey, Ateles geoffroyi",
        "382": "squirrel monkey, Saimiri sciureus",
        "383": "Madagascar cat, ring-tailed lemur, Lemur catta",
        "384": "indri, indris, Indri indri, Indri brevicaudatus",
        "385": "Indian elephant, Elephas maximus",
        "386": "African elephant, Loxodonta africana",
        "387": "lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens",
        "388": "giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca",
        "389": "barracouta, snoek",
        "390": "eel",
        "391": "coho, cohoe, coho salmon, blue jack, silver salmon, Oncorhynchus kisutch",
        "392": "rock beauty, Holocanthus tricolor",
        "393": "anemone fish",
        "394": "sturgeon",
        "395": "gar, garfish, garpike, billfish, Lepisosteus osseus",
        "396": "lionfish",
        "397": "puffer, pufferfish, blowfish, globefish",
        "398": "abacus",
        "399": "abaya",
        "400": "academic gown, academic robe, judge's robe",
        "401": "accordion, piano accordion, squeeze box",
        "402": "acoustic guitar",
        "403": "aircraft carrier, carrier, flattop, attack aircraft carrier",
        "404": "airliner",
        "405": "airship, dirigible",
        "406": "altar",
        "407": "ambulance",
        "408": "amphibian, amphibious vehicle",
        "409": "analog clock",
        "410": "apiary, bee house",
        "411": "apron",
        "412": "ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustbin, trash barrel, trash bin",
        "413": "assault rifle, assault gun",
        "414": "backpack, back pack, knapsack, packsack, rucksack, haversack",
        "415": "bakery, bakeshop, bakehouse",
        "416": "balance beam, beam",
        "417": "balloon",
        "418": "ballpoint, ballpoint pen, ballpen, Biro",
        "419": "Band Aid",
        "420": "banjo",
        "421": "bannister, banister, balustrade, balusters, handrail",
        "422": "barbell",
        "423": "barber chair",
        "424": "barbershop",
        "425": "barn",
        "426": "barometer",
        "427": "barrel, cask",
        "428": "barrow, garden cart, lawn cart, wheelbarrow",
        "429": "baseball",
        "430": "basketball",
        "431": "bassinet",
        "432": "bassoon",
        "433": "bathing cap, swimming cap",
        "434": "bath towel",
        "435": "bathtub, bathing tub, bath, tub",
        "436": "beach wagon, station wagon, wagon, estate car, beach waggon, station waggon, waggon",
        "437": "beacon, lighthouse, beacon light, pharos",
        "438": "beaker",
        "439": "bearskin, busby, shako",
        "440": "beer bottle",
        "441": "beer glass",
        "442": "bell cote, bell cot",
        "443": "bib",
        "444": "bicycle-built-for-two, tandem bicycle, tandem",
        "445": "bikini, two-piece",
        "446": "binder, ring-binder",
        "447": "binoculars, field glasses, opera glasses",
        "448": "birdhouse",
        "449": "boathouse",
        "450": "bobsled, bobsleigh, bob",
        "451": "bolo tie, bolo, bola tie, bola",
        "452": "bonnet, poke bonnet",
        "453": "bookcase",
        "454": "bookshop, bookstore, bookstall",
        "455": "bottlecap",
        "456": "bow",
        "457": "bow tie, bow-tie, bowtie",
        "458": "brass, memorial tablet, plaque",
        "459": "brassiere, bra, bandeau",
        "460": "breakwater, groin, groyne, mole, bulwark, seawall, jetty",
        "461": "breastplate, aegis, egis",
        "462": "broom",
        "463": "bucket, pail",
        "464": "buckle",
        "465": "bulletproof vest",
        "466": "bullet train, bullet",
        "467": "butcher shop, meat market",
        "468": "cab, hack, taxi, taxicab",
        "469": "caldron, cauldron",
        "470": "candle, taper, wax light",
        "471": "cannon",
        "472": "canoe",
        "473": "can opener, tin opener",
        "474": "cardigan",
        "475": "car mirror",
        "476": "carousel, carrousel, merry-go-round, roundabout, whirligig",
        "477": "carpenter's kit, tool kit",
        "478": "carton",
        "479": "car wheel",
        "480": "cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM",
        "481": "cassette",
        "482": "cassette player",
        "483": "castle",
        "484": "catamaran",
        "485": "CD player",
        "486": "cello, violoncello",
        "487": "cellular telephone, cellular phone, cellphone, cell, mobile phone",
        "488": "chain",
        "489": "chainlink fence",
        "490": "chain mail, ring mail, mail, chain armor, chain armour, ring armor, ring armour",
        "491": "chain saw, chainsaw",
        "492": "chest",
        "493": "chiffonier, commode",
        "494": "chime, bell, gong",
        "495": "china cabinet, china closet",
        "496": "Christmas stocking",
        "497": "church, church building",
        "498": "cinema, movie theater, movie theatre, movie house, picture palace",
        "499": "cleaver, meat cleaver, chopper",
        "500": "cliff dwelling",
        "501": "cloak",
        "502": "clog, geta, patten, sabot",
        "503": "cocktail shaker",
        "504": "coffee mug",
        "505": "coffeepot",
        "506": "coil, spiral, volute, whorl, helix",
        "507": "combination lock",
        "508": "computer keyboard, keypad",
        "509": "confectionery, confectionary, candy store",
        "510": "container ship, containership, container vessel",
        "511": "convertible",
        "512": "corkscrew, bottle screw",
        "513": "cornet, horn, trumpet, trump",
        "514": "cowboy boot",
        "515": "cowboy hat, ten-gallon hat",
        "516": "cradle",
        "517": "crane2",
        "518": "crash helmet",
        "519": "crate",
        "520": "crib, cot",
        "521": "Crock Pot",
        "522": "croquet ball",
        "523": "crutch",
        "524": "cuirass",
        "525": "dam, dike, dyke",
        "526": "desk",
        "527": "desktop computer",
        "528": "dial telephone, dial phone",
        "529": "diaper, nappy, napkin",
        "530": "digital clock",
        "531": "digital watch",
        "532": "dining table, board",
        "533": "dishrag, dishcloth",
        "534": "dishwasher, dish washer, dishwashing machine",
        "535": "disk brake, disc brake",
        "536": "dock, dockage, docking facility",
        "537": "dogsled, dog sled, dog sleigh",
        "538": "dome",
        "539": "doormat, welcome mat",
        "540": "drilling platform, offshore rig",
        "541": "drum, membranophone, tympan",
        "542": "drumstick",
        "543": "dumbbell",
        "544": "Dutch oven",
        "545": "electric fan, blower",
        "546": "electric guitar",
        "547": "electric locomotive",
        "548": "entertainment center",
        "549": "envelope",
        "550": "espresso maker",
        "551": "face powder",
        "552": "feather boa, boa",
        "553": "file, file cabinet, filing cabinet",
        "554": "fireboat",
        "555": "fire engine, fire truck",
        "556": "fire screen, fireguard",
        "557": "flagpole, flagstaff",
        "558": "flute, transverse flute",
        "559": "folding chair",
        "560": "football helmet",
        "561": "forklift",
        "562": "fountain",
        "563": "fountain pen",
        "564": "four-poster",
        "565": "freight car",
        "566": "French horn, horn",
        "567": "frying pan, frypan, skillet",
        "568": "fur coat",
        "569": "garbage truck, dustcart",
        "570": "gasmask, respirator, gas helmet",
        "571": "gas pump, gasoline pump, petrol pump, island dispenser",
        "572": "goblet",
        "573": "go-kart",
        "574": "golf ball",
        "575": "golfcart, golf cart",
        "576": "gondola",
        "577": "gong, tam-tam",
        "578": "gown",
        "579": "grand piano, grand",
        "580": "greenhouse, nursery, glasshouse",
        "581": "grille, radiator grille",
        "582": "grocery store, grocery, food market, market",
        "583": "guillotine",
        "584": "hair slide",
        "585": "hair spray",
        "586": "half track",
        "587": "hammer",
        "588": "hamper",
        "589": "hand blower, blow dryer, blow drier, hair dryer, hair drier",
        "590": "hand-held computer, hand-held microcomputer",
        "591": "handkerchief, hankie, hanky, hankey",
        "592": "hard disc, hard disk, fixed disk",
        "593": "harmonica, mouth organ, harp, mouth harp",
        "594": "harp",
        "595": "harvester, reaper",
        "596": "hatchet",
        "597": "holster",
        "598": "home theater, home theatre",
        "599": "honeycomb",
        "600": "hook, claw",
        "601": "hoopskirt, crinoline",
        "602": "horizontal bar, high bar",
        "603": "horse cart, horse-cart",
        "604": "hourglass",
        "605": "iPod",
        "606": "iron, smoothing iron",
        "607": "jack-o'-lantern",
        "608": "jean, blue jean, denim",
        "609": "jeep, landrover",
        "610": "jersey, T-shirt, tee shirt",
        "611": "jigsaw puzzle",
        "612": "jinrikisha, ricksha, rickshaw",
        "613": "joystick",
        "614": "kimono",
        "615": "knee pad",
        "616": "knot",
        "617": "lab coat, laboratory coat",
        "618": "ladle",
        "619": "lampshade, lamp shade",
        "620": "laptop, laptop computer",
        "621": "lawn mower, mower",
        "622": "lens cap, lens cover",
        "623": "letter opener, paper knife, paperknife",
        "624": "library",
        "625": "lifeboat",
        "626": "lighter, light, igniter, ignitor",
        "627": "limousine, limo",
        "628": "liner, ocean liner",
        "629": "lipstick, lip rouge",
        "630": "Loafer",
        "631": "lotion",
        "632": "loudspeaker, speaker, speaker unit, loudspeaker system, speaker system",
        "633": "loupe, jeweler's loupe",
        "634": "lumbermill, sawmill",
        "635": "magnetic compass",
        "636": "mailbag, postbag",
        "637": "mailbox, letter box",
        "638": "maillot",
        "639": "maillot, tank suit",
        "640": "manhole cover",
        "641": "maraca",
        "642": "marimba, xylophone",
        "643": "mask",
        "644": "matchstick",
        "645": "maypole",
        "646": "maze, labyrinth",
        "647": "measuring cup",
        "648": "medicine chest, medicine cabinet",
        "649": "megalith, megalithic structure",
        "650": "microphone, mike",
        "651": "microwave, microwave oven",
        "652": "military uniform",
        "653": "milk can",
        "654": "minibus",
        "655": "miniskirt, mini",
        "656": "minivan",
        "657": "missile",
        "658": "mitten",
        "659": "mixing bowl",
        "660": "mobile home, manufactured home",
        "661": "Model T",
        "662": "modem",
        "663": "monastery",
        "664": "monitor",
        "665": "moped",
        "666": "mortar",
        "667": "mortarboard",
        "668": "mosque",
        "669": "mosquito net",
        "670": "motor scooter, scooter",
        "671": "mountain bike, all-terrain bike, off-roader",
        "672": "mountain tent",
        "673": "mouse, computer mouse",
        "674": "mousetrap",
        "675": "moving van",
        "676": "muzzle",
        "677": "nail",
        "678": "neck brace",
        "679": "necklace",
        "680": "nipple",
        "681": "notebook, notebook computer",
        "682": "obelisk",
        "683": "oboe, hautboy, hautbois",
        "684": "ocarina, sweet potato",
        "685": "odometer, hodometer, mileometer, milometer",
        "686": "oil filter",
        "687": "organ, pipe organ",
        "688": "oscilloscope, scope, cathode-ray oscilloscope, CRO",
        "689": "overskirt",
        "690": "oxcart",
        "691": "oxygen mask",
        "692": "packet",
        "693": "paddle, boat paddle",
        "694": "paddlewheel, paddle wheel",
        "695": "padlock",
        "696": "paintbrush",
        "697": "pajama, pyjama, pj's, jammies",
        "698": "palace",
        "699": "panpipe, pandean pipe, syrinx",
        "700": "paper towel",
        "701": "parachute, chute",
        "702": "parallel bars, bars",
        "703": "park bench",
        "704": "parking meter",
        "705": "passenger car, coach, carriage",
        "706": "patio, terrace",
        "707": "pay-phone, pay-station",
        "708": "pedestal, plinth, footstall",
        "709": "pencil box, pencil case",
        "710": "pencil sharpener",
        "711": "perfume, essence",
        "712": "Petri dish",
        "713": "photocopier",
        "714": "pick, plectrum, plectron",
        "715": "pickelhaube",
        "716": "picket fence, paling",
        "717": "pickup, pickup truck",
        "718": "pier",
        "719": "piggy bank, penny bank",
        "720": "pill bottle",
        "721": "pillow",
        "722": "ping-pong ball",
        "723": "pinwheel",
        "724": "pirate, pirate ship",
        "725": "pitcher, ewer",
        "726": "plane, carpenter's plane, woodworking plane",
        "727": "planetarium",
        "728": "plastic bag",
        "729": "plate rack",
        "730": "plow, plough",
        "731": "plunger, plumber's helper",
        "732": "Polaroid camera, Polaroid Land camera",
        "733": "pole",
        "734": "police van, police wagon, paddy wagon, patrol wagon, wagon, black Maria",
        "735": "poncho",
        "736": "pool table, billiard table, snooker table",
        "737": "pop bottle, soda bottle",
        "738": "pot, flowerpot",
        "739": "potter's wheel",
        "740": "power drill",
        "741": "prayer rug, prayer mat",
        "742": "printer",
        "743": "prison, prison house",
        "744": "projectile, missile",
        "745": "projector",
        "746": "puck, hockey puck",
        "747": "punching bag, punch bag, punching ball, punchball",
        "748": "purse",
        "749": "quill, quill pen",
        "750": "quilt, comforter, comfort, puff",
        "751": "racer, race car, racing car",
        "752": "racket, racquet",
        "753": "radiator",
        "754": "radio, wireless",
        "755": "radio telescope, radio reflector",
        "756": "rain barrel",
        "757": "recreational vehicle, RV, R.V.",
        "758": "reel",
        "759": "reflex camera",
        "760": "refrigerator, icebox",
        "761": "remote control, remote",
        "762": "restaurant, eating house, eating place, eatery",
        "763": "revolver, six-gun, six-shooter",
        "764": "rifle",
        "765": "rocking chair, rocker",
        "766": "rotisserie",
        "767": "rubber eraser, rubber, pencil eraser",
        "768": "rugby ball",
        "769": "rule, ruler",
        "770": "running shoe",
        "771": "safe",
        "772": "safety pin",
        "773": "saltshaker, salt shaker",
        "774": "sandal",
        "775": "sarong",
        "776": "sax, saxophone",
        "777": "scabbard",
        "778": "scale, weighing machine",
        "779": "school bus",
        "780": "schooner",
        "781": "scoreboard",
        "782": "screen, CRT screen",
        "783": "screw",
        "784": "screwdriver",
        "785": "seat belt, seatbelt",
        "786": "sewing machine",
        "787": "shield, buckler",
        "788": "shoe shop, shoe-shop, shoe store",
        "789": "shoji",
        "790": "shopping basket",
        "791": "shopping cart",
        "792": "shovel",
        "793": "shower cap",
        "794": "shower curtain",
        "795": "ski",
        "796": "ski mask",
        "797": "sleeping bag",
        "798": "slide rule, slipstick",
        "799": "sliding door",
        "800": "slot, one-armed bandit",
        "801": "snorkel",
        "802": "snowmobile",
        "803": "snowplow, snowplough",
        "804": "soap dispenser",
        "805": "soccer ball",
        "806": "sock",
        "807": "solar dish, solar collector, solar furnace",
        "808": "sombrero",
        "809": "soup bowl",
        "810": "space bar",
        "811": "space heater",
        "812": "space shuttle",
        "813": "spatula",
        "814": "speedboat",
        "815": "spider web, spider's web",
        "816": "spindle",
        "817": "sports car, sport car",
        "818": "spotlight, spot",
        "819": "stage",
        "820": "steam locomotive",
        "821": "steel arch bridge",
        "822": "steel drum",
        "823": "stethoscope",
        "824": "stole",
        "825": "stone wall",
        "826": "stopwatch, stop watch",
        "827": "stove",
        "828": "strainer",
        "829": "streetcar, tram, tramcar, trolley, trolley car",
        "830": "stretcher",
        "831": "studio couch, day bed",
        "832": "stupa, tope",
        "833": "submarine, pigboat, sub, U-boat",
        "834": "suit, suit of clothes",
        "835": "sundial",
        "836": "sunglass",
        "837": "sunglasses, dark glasses, shades",
        "838": "sunscreen, sunblock, sun blocker",
        "839": "suspension bridge",
        "840": "swab, swob, mop",
        "841": "sweatshirt",
        "842": "swimming trunks, bathing trunks",
        "843": "swing",
        "844": "switch, electric switch, electrical switch",
        "845": "syringe",
        "846": "table lamp",
        "847": "tank, army tank, armored combat vehicle, armoured combat vehicle",
        "848": "tape player",
        "849": "teapot",
        "850": "teddy, teddy bear",
        "851": "television, television system",
        "852": "tennis ball",
        "853": "thatch, thatched roof",
        "854": "theater curtain, theatre curtain",
        "855": "thimble",
        "856": "thresher, thrasher, threshing machine",
        "857": "throne",
        "858": "tile roof",
        "859": "toaster",
        "860": "tobacco shop, tobacconist shop, tobacconist",
        "861": "toilet seat",
        "862": "torch",
        "863": "totem pole",
        "864": "tow truck, tow car, wrecker",
        "865": "toyshop",
        "866": "tractor",
        "867": "trailer truck, tractor trailer, trucking rig, rig, articulated lorry, semi",
        "868": "tray",
        "869": "trench coat",
        "870": "tricycle, trike, velocipede",
        "871": "trimaran",
        "872": "tripod",
        "873": "triumphal arch",
        "874": "trolleybus, trolley coach, trackless trolley",
        "875": "trombone",
        "876": "tub, vat",
        "877": "turnstile",
        "878": "typewriter keyboard",
        "879": "umbrella",
        "880": "unicycle, monocycle",
        "881": "upright, upright piano",
        "882": "vacuum, vacuum cleaner",
        "883": "vase",
        "884": "vault",
        "885": "velvet",
        "886": "vending machine",
        "887": "vestment",
        "888": "viaduct",
        "889": "violin, fiddle",
        "890": "volleyball",
        "891": "waffle iron",
        "892": "wall clock",
        "893": "wallet, billfold, notecase, pocketbook",
        "894": "wardrobe, closet, press",
        "895": "warplane, military plane",
        "896": "washbasin, handbasin, washbowl, lavabo, wash-hand basin",
        "897": "washer, automatic washer, washing machine",
        "898": "water bottle",
        "899": "water jug",
        "900": "water tower",
        "901": "whiskey jug",
        "902": "whistle",
        "903": "wig",
        "904": "window screen",
        "905": "window shade",
        "906": "Windsor tie",
        "907": "wine bottle",
        "908": "wing",
        "909": "wok",
        "910": "wooden spoon",
        "911": "wool, woolen, woollen",
        "912": "worm fence, snake fence, snake-rail fence, Virginia fence",
        "913": "wreck",
        "914": "yawl",
        "915": "yurt",
        "916": "web site, website, internet site, site",
        "917": "comic book",
        "918": "crossword puzzle, crossword",
        "919": "street sign",
        "920": "traffic light, traffic signal, stoplight",
        "921": "book jacket, dust cover, dust jacket, dust wrapper",
        "922": "menu",
        "923": "plate",
        "924": "guacamole",
        "925": "consomme",
        "926": "hot pot, hotpot",
        "927": "trifle",
        "928": "ice cream, icecream",
        "929": "ice lolly, lolly, lollipop, popsicle",
        "930": "French loaf",
        "931": "bagel, beigel",
        "932": "pretzel",
        "933": "cheeseburger",
        "934": "hotdog, hot dog, red hot",
        "935": "mashed potato",
        "936": "head cabbage",
        "937": "broccoli",
        "938": "cauliflower",
        "939": "zucchini, courgette",
        "940": "spaghetti squash",
        "941": "acorn squash",
        "942": "butternut squash",
        "943": "cucumber, cuke",
        "944": "artichoke, globe artichoke",
        "945": "bell pepper",
        "946": "cardoon",
        "947": "mushroom",
        "948": "Granny Smith",
        "949": "strawberry",
        "950": "orange",
        "951": "lemon",
        "952": "fig",
        "953": "pineapple, ananas",
        "954": "banana",
        "955": "jackfruit, jak, jack",
        "956": "custard apple",
        "957": "pomegranate",
        "958": "hay",
        "959": "carbonara",
        "960": "chocolate sauce, chocolate syrup",
        "961": "dough",
        "962": "meat loaf, meatloaf",
        "963": "pizza, pizza pie",
        "964": "potpie",
        "965": "burrito",
        "966": "red wine",
        "967": "espresso",
        "968": "cup",
        "969": "eggnog",
        "970": "alp",
        "971": "bubble",
        "972": "cliff, drop, drop-off",
        "973": "coral reef",
        "974": "geyser",
        "975": "lakeside, lakeshore",
        "976": "promontory, headland, head, foreland",
        "977": "sandbar, sand bar",
        "978": "seashore, coast, seacoast, sea-coast",
        "979": "valley, vale",
        "980": "volcano",
        "981": "ballplayer, baseball player",
        "982": "groom, bridegroom",
        "983": "scuba diver",
        "984": "rapeseed",
        "985": "daisy",
        "986": "yellow lady's slipper, yellow lady-slipper, Cypripedium calceolus, Cypripedium parviflorum",
        "987": "corn",
        "988": "acorn",
        "989": "hip, rose hip, rosehip",
        "990": "buckeye, horse chestnut, conker",
        "991": "coral fungus",
        "992": "agaric",
        "993": "gyromitra",
        "994": "stinkhorn, carrion fungus",
        "995": "earthstar",
        "996": "hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa",
        "997": "bolete",
        "998": "ear, spike, capitulum",
        "999": "toilet tissue, toilet paper, bathroom tissue",
    }
)

IMAGENET2012_GENERIC_CLASSES = OrderedDict(
    {
        "0": "cypriniform fish",
        "1": "cypriniform fish",
        "2": "shark",
        "3": "shark",
        "4": "elasmobranch",
        "5": "elasmobranch",
        "6": "elasmobranch",
        "7": "vertebrate",
        "8": "vertebrate",
        "9": "bird",
        "10": "oscine",
        "11": "oscine",
        "12": "oscine",
        "13": "oscine",
        "14": "finch",
        "15": "oscine",
        "16": "thrush",
        "17": "oscine",
        "18": "oscine",
        "19": "oscine",
        "20": "passerine",
        "21": "bird of prey",
        "22": "bird of prey",
        "23": "bird",
        "24": "bird of prey",
        "25": "amphibian",
        "26": "salamander",
        "27": "salamander",
        "28": "salamander",
        "29": "salamander",
        "30": "frog",
        "31": "amphibian",
        "32": "amphibian",
        "33": "turtle",
        "34": "turtle",
        "35": "chelonian",
        "36": "chelonian",
        "37": "chelonian",
        "38": "lizard",
        "39": "lizard",
        "40": "lizard",
        "41": "lizard",
        "42": "lizard",
        "43": "lizard",
        "44": "lizard",
        "45": "lizard",
        "46": "lizard",
        "47": "lizard",
        "48": "lizard",
        "49": "crocodilian reptile",
        "50": "crocodilian reptile",
        "51": "ornithischian",
        "52": "snake",
        "53": "snake",
        "54": "snake",
        "55": "snake",
        "56": "snake",
        "57": "snake",
        "58": "snake",
        "59": "snake",
        "60": "snake",
        "61": "constrictor",
        "62": "boa",
        "63": "elapid",
        "64": "mamba",
        "65": "diapsid",
        "66": "snake",
        "67": "pit viper",
        "68": "pit viper",
        "69": "invertebrate",
        "70": "arthropod",
        "71": "arthropod",
        "72": "arachnid",
        "73": "arachnid",
        "74": "arachnid",
        "75": "arachnid",
        "76": "arachnid",
        "77": "arachnid",
        "78": "arachnid",
        "79": "invertebrate",
        "80": "game bird",
        "81": "game bird",
        "82": "game bird",
        "83": "game bird",
        "84": "pheasant",
        "85": "game bird",
        "86": "game bird",
        "87": "bird",
        "88": "bird",
        "89": "parrot",
        "90": "parrot",
        "91": "cuculiform bird",
        "92": "bird",
        "93": "bird",
        "94": "bird",
        "95": "bird",
        "96": "bird",
        "97": "anseriform bird",
        "98": "sea duck",
        "99": "waterfowl",
        "100": "aquatic bird",
        "101": "vertebrate",
        "102": "prototherian",
        "103": "prototherian",
        "104": "marsupial",
        "105": "marsupial",
        "106": "metatherian",
        "107": "invertebrate",
        "108": "coelenterate",
        "109": "coral",
        "110": "invertebrate",
        "111": "invertebrate",
        "112": "mollusk",
        "113": "mollusk",
        "114": "mollusk",
        "115": "mollusk",
        "116": "invertebrate",
        "117": "mollusk",
        "118": "decapod crustacean",
        "119": "decapod crustacean",
        "120": "decapod crustacean",
        "121": "decapod crustacean",
        "122": "lobster",
        "123": "decapod crustacean",
        "124": "crustacean",
        "125": "crustacean",
        "126": "crustacean",
        "127": "wading bird",
        "128": "wading bird",
        "129": "aquatic bird",
        "130": "aquatic bird",
        "131": "wading bird",
        "132": "heron",
        "133": "wading bird",
        "134": "aquatic bird",
        "135": "aquatic bird",
        "136": "gallinule",
        "137": "rail",
        "138": "aquatic bird",
        "139": "plover",
        "140": "shorebird",
        "141": "shorebird",
        "142": "shorebird",
        "143": "wading bird",
        "144": "seabird",
        "145": "sphenisciform seabird",
        "146": "seabird",
        "147": "whale",
        "148": "toothed whale",
        "149": "aquatic mammal",
        "150": "seal",
        "151": "dog",
        "152": "dog",
        "153": "dog",
        "154": "dog",
        "155": "dog",
        "156": "toy spaniel",
        "157": "toy dog",
        "158": "dog",
        "159": "dog",
        "160": "hunting dog",
        "161": "hunting dog",
        "162": "hunting dog",
        "163": "hunting dog",
        "164": "hunting dog",
        "165": "hound",
        "166": "hound",
        "167": "hound",
        "168": "hunting dog",
        "169": "hound",
        "170": "hound",
        "171": "hound",
        "172": "hound",
        "173": "hunting dog",
        "174": "hunting dog",
        "175": "hunting dog",
        "176": "hunting dog",
        "177": "hunting dog",
        "178": "hunting dog",
        "179": "terrier",
        "180": "terrier",
        "181": "hunting dog",
        "182": "hunting dog",
        "183": "hunting dog",
        "184": "hunting dog",
        "185": "hunting dog",
        "186": "hunting dog",
        "187": "hunting dog",
        "188": "terrier",
        "189": "terrier",
        "190": "wirehair",
        "191": "hunting dog",
        "192": "hunting dog",
        "193": "hunting dog",
        "194": "hunting dog",
        "195": "hunting dog",
        "196": "terrier",
        "197": "terrier",
        "198": "terrier",
        "199": "hunting dog",
        "200": "hunting dog",
        "201": "hunting dog",
        "202": "hunting dog",
        "203": "hunting dog",
        "204": "hunting dog",
        "205": "sporting dog",
        "206": "sporting dog",
        "207": "sporting dog",
        "208": "sporting dog",
        "209": "sporting dog",
        "210": "sporting dog",
        "211": "sporting dog",
        "212": "sporting dog",
        "213": "sporting dog",
        "214": "sporting dog",
        "215": "sporting dog",
        "216": "sporting dog",
        "217": "spaniel",
        "218": "spaniel",
        "219": "sporting dog",
        "220": "sporting dog",
        "221": "spaniel",
        "222": "working dog",
        "223": "working dog",
        "224": "shepherd dog",
        "225": "shepherd dog",
        "226": "working dog",
        "227": "working dog",
        "228": "working dog",
        "229": "working dog",
        "230": "working dog",
        "231": "working dog",
        "232": "working dog",
        "233": "working dog",
        "234": "working dog",
        "235": "working dog",
        "236": "watchdog",
        "237": "watchdog",
        "238": "working dog",
        "239": "working dog",
        "240": "working dog",
        "241": "working dog",
        "242": "dog",
        "243": "dog",
        "244": "working dog",
        "245": "working dog",
        "246": "dog",
        "247": "dog",
        "248": "dog",
        "249": "working dog",
        "250": "working dog",
        "251": "canine",
        "252": "watchdog",
        "253": "canine",
        "254": "canine",
        "255": "canine",
        "256": "canine",
        "257": "canine",
        "258": "dog",
        "259": "dog",
        "260": "dog",
        "261": "dog",
        "262": "dog",
        "263": "dog",
        "264": "dog",
        "265": "dog",
        "266": "dog",
        "267": "dog",
        "268": "canine",
        "269": "canine",
        "270": "canine",
        "271": "canine",
        "272": "canine",
        "273": "canine",
        "274": "canine",
        "275": "canine",
        "276": "carnivore",
        "277": "canine",
        "278": "canine",
        "279": "canine",
        "280": "canine",
        "281": "cat",
        "282": "cat",
        "283": "cat",
        "284": "cat",
        "285": "cat",
        "286": "cat",
        "287": "cat",
        "288": "feline",
        "289": "feline",
        "290": "feline",
        "291": "feline",
        "292": "feline",
        "293": "feline",
        "294": "carnivore",
        "295": "carnivore",
        "296": "carnivore",
        "297": "carnivore",
        "298": "carnivore",
        "299": "carnivore",
        "300": "insect",
        "301": "insect",
        "302": "insect",
        "303": "insect",
        "304": "insect",
        "305": "lamellicorn beetle",
        "306": "lamellicorn beetle",
        "307": "insect",
        "308": "insect",
        "309": "insect",
        "310": "insect",
        "311": "insect",
        "312": "insect",
        "313": "insect",
        "314": "insect",
        "315": "insect",
        "316": "insect",
        "317": "insect",
        "318": "insect",
        "319": "insect",
        "320": "insect",
        "321": "butterfly",
        "322": "lepidopterous insect",
        "323": "butterfly",
        "324": "butterfly",
        "325": "lepidopterous insect",
        "326": "lepidopterous insect",
        "327": "invertebrate",
        "328": "invertebrate",
        "329": "invertebrate",
        "330": "leporid",
        "331": "lagomorph",
        "332": "leporid",
        "333": "placental",
        "334": "placental",
        "335": "squirrel",
        "336": "placental",
        "337": "placental",
        "338": "rodent",
        "339": "equine",
        "340": "odd-toed ungulate",
        "341": "even-toed ungulate",
        "342": "even-toed ungulate",
        "343": "even-toed ungulate",
        "344": "ungulate",
        "345": "bovine",
        "346": "bovid",
        "347": "ruminant",
        "348": "bovid",
        "349": "wild sheep",
        "350": "goat",
        "351": "bovid",
        "352": "bovid",
        "353": "bovid",
        "354": "even-toed ungulate",
        "355": "ungulate",
        "356": "carnivore",
        "357": "carnivore",
        "358": "carnivore",
        "359": "carnivore",
        "360": "carnivore",
        "361": "carnivore",
        "362": "carnivore",
        "363": "placental",
        "364": "edentate",
        "365": "anthropoid ape",
        "366": "anthropoid ape",
        "367": "anthropoid ape",
        "368": "anthropoid ape",
        "369": "anthropoid ape",
        "370": "monkey",
        "371": "monkey",
        "372": "monkey",
        "373": "monkey",
        "374": "monkey",
        "375": "monkey",
        "376": "monkey",
        "377": "monkey",
        "378": "monkey",
        "379": "monkey",
        "380": "monkey",
        "381": "monkey",
        "382": "monkey",
        "383": "primate",
        "384": "primate",
        "385": "pachyderm",
        "386": "pachyderm",
        "387": "carnivore",
        "388": "carnivore",
        "389": "fish",
        "390": "teleost fish",
        "391": "food fish",
        "392": "percoid fish",
        "393": "percoid fish",
        "394": "teleost fish",
        "395": "teleost fish",
        "396": "scorpaenoid",
        "397": "spiny-finned fish",
        "398": "machine",
        "399": "garment",
        "400": "outerwear",
        "401": "wind instrument",
        "402": "stringed instrument",
        "403": "military vehicle",
        "404": "heavier-than-air craft",
        "405": "aircraft",
        "406": "artifact",
        "407": "motor vehicle",
        "408": "self-propelled vehicle",
        "409": "timepiece",
        "410": "outbuilding",
        "411": "clothing",
        "412": "container",
        "413": "machine gun",
        "414": "container",
        "415": "mercantile establishment",
        "416": "sports equipment",
        "417": "aircraft",
        "418": "writing implement",
        "419": "bandage",
        "420": "musical instrument",
        "421": "obstruction",
        "422": "sports equipment",
        "423": "seat",
        "424": "mercantile establishment",
        "425": "building",
        "426": "instrument",
        "427": "container",
        "428": "wheeled vehicle",
        "429": "game equipment",
        "430": "game equipment",
        "431": "furniture",
        "432": "beating-reed instrument",
        "433": "headdress",
        "434": "linen",
        "435": "container",
        "436": "motor vehicle",
        "437": "structure",
        "438": "vessel",
        "439": "headdress",
        "440": "vessel",
        "441": "container",
        "442": "protective covering",
        "443": "fabric",
        "444": "wheeled vehicle",
        "445": "garment",
        "446": "covering",
        "447": "instrument",
        "448": "protective covering",
        "449": "outbuilding",
        "450": "vehicle",
        "451": "neckwear",
        "452": "headdress",
        "453": "furnishing",
        "454": "mercantile establishment",
        "455": "top",
        "456": "instrument",
        "457": "neckwear",
        "458": "structure",
        "459": "clothing",
        "460": "obstruction",
        "461": "plate",
        "462": "implement",
        "463": "container",
        "464": "restraint",
        "465": "garment",
        "466": "train",
        "467": "mercantile establishment",
        "468": "motor vehicle",
        "469": "vessel",
        "470": "source of illumination",
        "471": "weapon",
        "472": "boat",
        "473": "hand tool",
        "474": "garment",
        "475": "reflector",
        "476": "mechanical device",
        "477": "gear",
        "478": "container",
        "479": "machine",
        "480": "device",
        "481": "instrumentality",
        "482": "equipment",
        "483": "defensive structure",
        "484": "sailing vessel",
        "485": "equipment",
        "486": "stringed instrument",
        "487": "telephone",
        "488": "attachment",
        "489": "barrier",
        "490": "armor",
        "491": "power tool",
        "492": "container",
        "493": "furniture",
        "494": "musical instrument",
        "495": "furniture",
        "496": "hosiery",
        "497": "building",
        "498": "building",
        "499": "edge tool",
        "500": "housing",
        "501": "garment",
        "502": "covering",
        "503": "container",
        "504": "drinking vessel",
        "505": "vessel",
        "506": "artifact",
        "507": "fastener",
        "508": "peripheral",
        "509": "mercantile establishment",
        "510": "ship",
        "511": "motor vehicle",
        "512": "opener",
        "513": "wind instrument",
        "514": "footwear",
        "515": "headdress",
        "516": "furniture",
        "517": "device",
        "518": "headdress",
        "519": "container",
        "520": "furniture",
        "521": "cooking utensil",
        "522": "game equipment",
        "523": "stick",
        "524": "armor",
        "525": "obstruction",
        "526": "furniture",
        "527": "digital computer",
        "528": "electronic equipment",
        "529": "clothing",
        "530": "timepiece",
        "531": "timepiece",
        "532": "furniture",
        "533": "fabric",
        "534": "home appliance",
        "535": "brake system",
        "536": "structure",
        "537": "vehicle",
        "538": "protective covering",
        "539": "floor cover",
        "540": "rig",
        "541": "musical instrument",
        "542": "implement",
        "543": "sports equipment",
        "544": "kitchen appliance",
        "545": "device",
        "546": "stringed instrument",
        "547": "self-propelled vehicle",
        "548": "furniture",
        "549": "instrumentality",
        "550": "kitchen appliance",
        "551": "cosmetic",
        "552": "garment",
        "553": "furniture",
        "554": "vessel",
        "555": "motor vehicle",
        "556": "protective covering",
        "557": "stick",
        "558": "wind instrument",
        "559": "seat",
        "560": "headdress",
        "561": "wheeled vehicle",
        "562": "artifact",
        "563": "writing implement",
        "564": "bedroom furniture",
        "565": "wheeled vehicle",
        "566": "wind instrument",
        "567": "cooking utensil",
        "568": "overgarment",
        "569": "motor vehicle",
        "570": "protective covering",
        "571": "mechanical device",
        "572": "container",
        "573": "self-propelled vehicle",
        "574": "game equipment",
        "575": "self-propelled vehicle",
        "576": "vessel",
        "577": "musical instrument",
        "578": "woman's clothing",
        "579": "stringed instrument",
        "580": "structure",
        "581": "barrier",
        "582": "mercantile establishment",
        "583": "instrument",
        "584": "fastener",
        "585": "instrumentality",
        "586": "self-propelled vehicle",
        "587": "tool",
        "588": "container",
        "589": "appliance",
        "590": "personal computer",
        "591": "fabric",
        "592": "memory device",
        "593": "wind instrument",
        "594": "stringed instrument",
        "595": "machine",
        "596": "edge tool",
        "597": "protective covering",
        "598": "building",
        "599": "supporting structure",
        "600": "mechanism",
        "601": "garment",
        "602": "sports equipment",
        "603": "wagon",
        "604": "timepiece",
        "605": "reproducer",
        "606": "appliance",
        "607": "lamp",
        "608": "apparel",
        "609": "motor vehicle",
        "610": "garment",
        "611": "game",
        "612": "wagon",
        "613": "peripheral",
        "614": "garment",
        "615": "clothing",
        "616": "restraint",
        "617": "overgarment",
        "618": "container",
        "619": "protective covering",
        "620": "personal computer",
        "621": "tool",
        "622": "protective covering",
        "623": "edge tool",
        "624": "structure",
        "625": "boat",
        "626": "instrumentality",
        "627": "motor vehicle",
        "628": "ship",
        "629": "cosmetic",
        "630": "footwear",
        "631": "instrumentality",
        "632": "transducer",
        "633": "light microscope",
        "634": "plant",
        "635": "navigational instrument",
        "636": "container",
        "637": "container",
        "638": "hosiery",
        "639": "garment",
        "640": "covering",
        "641": "musical instrument",
        "642": "musical instrument",
        "643": "attire",
        "644": "implement",
        "645": "upright",
        "646": "instrumentality",
        "647": "container",
        "648": "furniture",
        "649": "structure",
        "650": "transducer",
        "651": "home appliance",
        "652": "clothing",
        "653": "container",
        "654": "public transport",
        "655": "garment",
        "656": "van",
        "657": "vehicle",
        "658": "handwear",
        "659": "dish",
        "660": "structure",
        "661": "motor vehicle",
        "662": "equipment",
        "663": "residence",
        "664": "equipment",
        "665": "motorcycle",
        "666": "container",
        "667": "headdress",
        "668": "building",
        "669": "protective covering",
        "670": "vehicle",
        "671": "wheeled vehicle",
        "672": "shelter",
        "673": "device",
        "674": "device",
        "675": "truck",
        "676": "device",
        "677": "restraint",
        "678": "support",
        "679": "adornment",
        "680": "top",
        "681": "personal computer",
        "682": "structure",
        "683": "beating-reed instrument",
        "684": "musical instrument",
        "685": "measuring instrument",
        "686": "device",
        "687": "musical instrument",
        "688": "equipment",
        "689": "garment",
        "690": "wagon",
        "691": "device",
        "692": "container",
        "693": "implement",
        "694": "machine",
        "695": "fastener",
        "696": "implement",
        "697": "clothing",
        "698": "house",
        "699": "wind instrument",
        "700": "piece of cloth",
        "701": "equipment",
        "702": "sports equipment",
        "703": "seat",
        "704": "timepiece",
        "705": "wheeled vehicle",
        "706": "structure",
        "707": "electronic equipment",
        "708": "supporting structure",
        "709": "container",
        "710": "implement",
        "711": "instrumentality",
        "712": "crockery",
        "713": "apparatus",
        "714": "instrumentality",
        "715": "armor plate",
        "716": "barrier",
        "717": "motor vehicle",
        "718": "device",
        "719": "container",
        "720": "vessel",
        "721": "padding",
        "722": "game equipment",
        "723": "machine",
        "724": "vessel",
        "725": "container",
        "726": "tool",
        "727": "structure",
        "728": "container",
        "729": "framework",
        "730": "implement",
        "731": "tool",
        "732": "photographic equipment",
        "733": "implement",
        "734": "truck",
        "735": "overgarment",
        "736": "furniture",
        "737": "vessel",
        "738": "instrumentality",
        "739": "machine",
        "740": "tool",
        "741": "floor cover",
        "742": "electronic equipment",
        "743": "penal institution",
        "744": "instrument",
        "745": "instrument",
        "746": "plate",
        "747": "game equipment",
        "748": "container",
        "749": "writing implement",
        "750": "cloth covering",
        "751": "motor vehicle",
        "752": "implement",
        "753": "device",
        "754": "system",
        "755": "telescope",
        "756": "pool",
        "757": "wheeled vehicle",
        "758": "mechanical device",
        "759": "photographic equipment",
        "760": "home appliance",
        "761": "instrumentality",
        "762": "structure",
        "763": "firearm",
        "764": "gun",
        "765": "seat",
        "766": "kitchen appliance",
        "767": "implement",
        "768": "game equipment",
        "769": "measuring instrument",
        "770": "footwear",
        "771": "box",
        "772": "fastener",
        "773": "container",
        "774": "footwear",
        "775": "garment",
        "776": "beating-reed instrument",
        "777": "protective covering",
        "778": "instrument",
        "779": "public transport",
        "780": "vessel",
        "781": "sheet",
        "782": "electronic device",
        "783": "restraint",
        "784": "tool",
        "785": "belt",
        "786": "appliance",
        "787": "protective covering",
        "788": "mercantile establishment",
        "789": "covering",
        "790": "container",
        "791": "wheeled vehicle",
        "792": "tool",
        "793": "headdress",
        "794": "blind",
        "795": "device",
        "796": "mask",
        "797": "container",
        "798": "computer",
        "799": "movable barrier",
        "800": "machine",
        "801": "device",
        "802": "self-propelled vehicle",
        "803": "self-propelled vehicle",
        "804": "container",
        "805": "game equipment",
        "806": "footwear",
        "807": "device",
        "808": "headdress",
        "809": "dish",
        "810": "lever",
        "811": "device",
        "812": "craft",
        "813": "cooking utensil",
        "814": "boat",
        "815": "trap",
        "816": "implement",
        "817": "motor vehicle",
        "818": "source of illumination",
        "819": "horizontal surface",
        "820": "self-propelled vehicle",
        "821": "structure",
        "822": "musical instrument",
        "823": "instrument",
        "824": "garment",
        "825": "barrier",
        "826": "timepiece",
        "827": "device",
        "828": "device",
        "829": "wheeled vehicle",
        "830": "conveyance",
        "831": "sofa",
        "832": "place of worship",
        "833": "warship",
        "834": "clothing",
        "835": "measuring instrument",
        "836": "lens",
        "837": "optical instrument",
        "838": "toiletry",
        "839": "structure",
        "840": "implement",
        "841": "sweater",
        "842": "garment",
        "843": "artifact",
        "844": "mechanism",
        "845": "instrument",
        "846": "furniture",
        "847": "self-propelled vehicle",
        "848": "equipment",
        "849": "vessel",
        "850": "artifact",
        "851": "communication system",
        "852": "game equipment",
        "853": "protective covering",
        "854": "blind",
        "855": "protective covering",
        "856": "machine",
        "857": "chair",
        "858": "protective covering",
        "859": "home appliance",
        "860": "mercantile establishment",
        "861": "furniture",
        "862": "source of illumination",
        "863": "design",
        "864": "motor vehicle",
        "865": "mercantile establishment",
        "866": "wheeled vehicle",
        "867": "motor vehicle",
        "868": "container",
        "869": "coat",
        "870": "vehicle",
        "871": "sailing vessel",
        "872": "support",
        "873": "structure",
        "874": "public transport",
        "875": "wind instrument",
        "876": "container",
        "877": "movable barrier",
        "878": "device",
        "879": "shelter",
        "880": "vehicle",
        "881": "stringed instrument",
        "882": "appliance",
        "883": "vessel",
        "884": "protective covering",
        "885": "artifact",
        "886": "machine",
        "887": "outerwear",
        "888": "structure",
        "889": "stringed instrument",
        "890": "game equipment",
        "891": "home appliance",
        "892": "timepiece",
        "893": "container",
        "894": "furnishing",
        "895": "vehicle",
        "896": "vessel",
        "897": "home appliance",
        "898": "vessel",
        "899": "bottle",
        "900": "tank",
        "901": "bottle",
        "902": "device",
        "903": "attire",
        "904": "protective covering",
        "905": "blind",
        "906": "neckwear",
        "907": "vessel",
        "908": "device",
        "909": "cooking utensil",
        "910": "cutlery",
        "911": "artifact",
        "912": "fence",
        "913": "vessel",
        "914": "boat",
        "915": "housing",
        "916": "machine",
        "917": "publication",
        "918": "game",
        "919": "street sign",
        "920": "traffic light",
        "921": "wrapping",
        "922": "menu",
        "923": "artifact",
        "924": "dip",
        "925": "dish",
        "926": "dish",
        "927": "dessert",
        "928": "dessert",
        "929": "dessert",
        "930": "french loaf",
        "931": "bun",
        "932": "pretzel",
        "933": "sandwich",
        "934": "sandwich",
        "935": "solanaceous vegetable",
        "936": "cruciferous vegetable",
        "937": "vegetable",
        "938": "vegetable",
        "939": "squash",
        "940": "squash",
        "941": "squash",
        "942": "squash",
        "943": "vegetable",
        "944": "vegetable",
        "945": "pepper",
        "946": "vegetable",
        "947": "vegetable",
        "948": "apple",
        "949": "edible fruit",
        "950": "edible fruit",
        "951": "edible fruit",
        "952": "fruit",
        "953": "fruit",
        "954": "fruit",
        "955": "fruit",
        "956": "fruit",
        "957": "fruit",
        "958": "feed",
        "959": "carbonara",
        "960": "sauce",
        "961": "foodstuff",
        "962": "nutriment",
        "963": "nutriment",
        "964": "nutriment",
        "965": "nutriment",
        "966": "alcohol",
        "967": "beverage",
        "968": "mixed drink",
        "969": "mixed drink",
        "970": "natural elevation",
        "971": "bubble",
        "972": "geological formation",
        "973": "ridge",
        "974": "geological formation",
        "975": "geological formation",
        "976": "geological formation",
        "977": "barrier",
        "978": "geological formation",
        "979": "geological formation",
        "980": "natural elevation",
        "981": "contestant",
        "982": "associate",
        "983": "explorer",
        "984": "seed",
        "985": "angiosperm",
        "986": "orchid",
        "987": "grain",
        "988": "plant reproductive structure",
        "989": "plant reproductive structure",
        "990": "fruit",
        "991": "organism",
        "992": "fungus",
        "993": "organism",
        "994": "organism",
        "995": "organism",
        "996": "organism",
        "997": "organism",
        "998": "plant reproductive structure",
        "999": "toilet tissue",
    }
)