# coding=utf-8
# Copyright 2022 the HuggingFace Datasets Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from collections import OrderedDict


IMAGENET_CLASSES = OrderedDict(
    {
        "0": "tench, Tinca tinca",
        "1": "goldfish, Carassius auratus",
        "2": "great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias",
        "3": "tiger shark, Galeocerdo cuvieri",
        "4": "hammerhead, hammerhead shark",
        "5": "electric ray, crampfish, numbfish, torpedo",
        "6": "stingray",
        "7": "cock",
        "8": "hen",
        "9": "ostrich, Struthio camelus",
        "10": "brambling, Fringilla montifringilla",
        "11": "goldfinch, Carduelis carduelis",
        "12": "house finch, linnet, Carpodacus mexicanus",
        "13": "junco, snowbird",
        "14": "indigo bunting, indigo finch, indigo bird, Passerina cyanea",
        "15": "robin, American robin, Turdus migratorius",
        "16": "bulbul",
        "17": "jay",
        "18": "magpie",
        "19": "chickadee",
        "20": "water ouzel, dipper",
        "21": "kite",
        "22": "bald eagle, American eagle, Haliaeetus leucocephalus",
        "23": "vulture",
        "24": "great grey owl, great gray owl, Strix nebulosa",
        "25": "European fire salamander, Salamandra salamandra",
        "26": "common newt, Triturus vulgaris",
        "27": "eft",
        "28": "spotted salamander, Ambystoma maculatum",
        "29": "axolotl, mud puppy, Ambystoma mexicanum",
        "30": "bullfrog, Rana catesbeiana",
        "31": "tree frog, tree-frog",
        "32": "tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui",
        "33": "loggerhead, loggerhead turtle, Caretta caretta",
        "34": "leatherback turtle, leatherback, leathery turtle, Dermochelys coriacea",
        "35": "mud turtle",
        "36": "terrapin",
        "37": "box turtle, box tortoise",
        "38": "banded gecko",
        "39": "common iguana, iguana, Iguana iguana",
        "40": "American chameleon, anole, Anolis carolinensis",
        "41": "whiptail, whiptail lizard",
        "42": "agama",
        "43": "frilled lizard, Chlamydosaurus kingi",
        "44": "alligator lizard",
        "45": "Gila monster, Heloderma suspectum",
        "46": "green lizard, Lacerta viridis",
        "47": "African chameleon, Chamaeleo chamaeleon",
        "48": "Komodo dragon, Komodo lizard, dragon lizard, giant lizard, Varanus komodoensis",
        "49": "African crocodile, Nile crocodile, Crocodylus niloticus",
        "50": "American alligator, Alligator mississipiensis",
        "51": "triceratops",
        "52": "thunder snake, worm snake, Carphophis amoenus",
        "53": "ringneck snake, ring-necked snake, ring snake",
        "54": "hognose snake, puff adder, sand viper",
        "55": "green snake, grass snake",
        "56": "king snake, kingsnake",
        "57": "garter snake, grass snake",
        "58": "water snake",
        "59": "vine snake",
        "60": "night snake, Hypsiglena torquata",
        "61": "boa constrictor, Constrictor constrictor",
        "62": "rock python, rock snake, Python sebae",
        "63": "Indian cobra, Naja naja",
        "64": "green mamba",
        "65": "sea snake",
        "66": "horned viper, cerastes, sand viper, horned asp, Cerastes cornutus",
        "67": "diamondback, diamondback rattlesnake, Crotalus adamanteus",
        "68": "sidewinder, horned rattlesnake, Crotalus cerastes",
        "69": "trilobite",
        "70": "harvestman, daddy longlegs, Phalangium opilio",
        "71": "scorpion",
        "72": "black and gold garden spider, Argiope aurantia",
        "73": "barn spider, Araneus cavaticus",
        "74": "garden spider, Aranea diademata",
        "75": "black widow, Latrodectus mactans",
        "76": "tarantula",
        "77": "wolf spider, hunting spider",
        "78": "tick",
        "79": "centipede",
        "80": "black grouse",
        "81": "ptarmigan",
        "82": "ruffed grouse, partridge, Bonasa umbellus",
        "83": "prairie chicken, prairie grouse, prairie fowl",
        "84": "peacock",
        "85": "quail",
        "86": "partridge",
        "87": "African grey, African gray, Psittacus erithacus",
        "88": "macaw",
        "89": "sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita",
        "90": "lorikeet",
        "91": "coucal",
        "92": "bee eater",
        "93": "hornbill",
        "94": "hummingbird",
        "95": "jacamar",
        "96": "toucan",
        "97": "drake",
        "98": "red-breasted merganser, Mergus serrator",
        "99": "goose",
        "100": "black swan, Cygnus atratus",
        "101": "tusker",
        "102": "echidna, spiny anteater, anteater",
        "103": "platypus, duckbill, duckbilled platypus, duck-billed platypus, Ornithorhynchus anatinus",
        "104": "wallaby, brush kangaroo",
        "105": "koala, koala bear, kangaroo bear, native bear, Phascolarctos cinereus",
        "106": "wombat",
        "107": "jellyfish",
        "108": "sea anemone, anemone",
        "109": "brain coral",
        "110": "flatworm, platyhelminth",
        "111": "nematode, nematode worm, roundworm",
        "112": "conch",
        "113": "snail",
        "114": "slug",
        "115": "sea slug, nudibranch",
        "116": "chiton, coat-of-mail shell, sea cradle, polyplacophore",
        "117": "chambered nautilus, pearly nautilus, nautilus",
        "118": "Dungeness crab, Cancer magister",
        "119": "rock crab, Cancer irroratus",
        "120": "fiddler crab",
        "121": "king crab, Alaska crab, Alaskan king crab, Alaska king crab, Paralithodes camtschatica",
        "122": "American lobster, Northern lobster, Maine lobster, Homarus americanus",
        "123": "spiny lobster, langouste, rock lobster, crawfish, crayfish, sea crawfish",
        "124": "crayfish, crawfish, crawdad, crawdaddy",
        "125": "hermit crab",
        "126": "isopod",
        "127": "white stork, Ciconia ciconia",
        "128": "black stork, Ciconia nigra",
        "129": "spoonbill",
        "130": "flamingo",
        "131": "little blue heron, Egretta caerulea",
        "132": "American egret, great white heron, Egretta albus",
        "133": "bittern",
        "134": "crane",
        "135": "limpkin, Aramus pictus",
        "136": "European gallinule, Porphyrio porphyrio",
        "137": "American coot, marsh hen, mud hen, water hen, Fulica americana",
        "138": "bustard",
        "139": "ruddy turnstone, Arenaria interpres",
        "140": "red-backed sandpiper, dunlin, Erolia alpina",
        "141": "redshank, Tringa totanus",
        "142": "dowitcher",
        "143": "oystercatcher, oyster catcher",
        "144": "pelican",
        "145": "king penguin, Aptenodytes patagonica",
        "146": "albatross, mollymawk",
        "147": "grey whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus",
        "148": "killer whale, killer, orca, grampus, sea wolf, Orcinus orca",
        "149": "dugong, Dugong dugon",
        "150": "sea lion",
        "151": "Chihuahua",
        "152": "Japanese spaniel",
        "153": "Maltese dog, Maltese terrier, Maltese",
        "154": "Pekinese, Pekingese, Peke",
        "155": "Shih-Tzu",
        "156": "Blenheim spaniel",
        "157": "papillon",
        "158": "toy terrier",
        "159": "Rhodesian ridgeback",
        "160": "Afghan hound, Afghan",
        "161": "basset, basset hound",
        "162": "beagle",
        "163": "bloodhound, sleuthhound",
        "164": "bluetick",
        "165": "black-and-tan coonhound",
        "166": "Walker hound, Walker foxhound",
        "167": "English foxhound",
        "168": "redbone",
        "169": "borzoi, Russian wolfhound",
        "170": "Irish wolfhound",
        "171": "Italian greyhound",
        "172": "whippet",
        "173": "Ibizan hound, Ibizan Podenco",
        "174": "Norwegian elkhound, elkhound",
        "175": "otterhound, otter hound",
        "176": "Saluki, gazelle hound",
        "177": "Scottish deerhound, deerhound",
        "178": "Weimaraner",
        "179": "Staffordshire bullterrier, Staffordshire bull terrier",
        "180": "American Staffordshire terrier, Staffordshire terrier, American pit bull terrier, pit bull terrier",
        "181": "Bedlington terrier",
        "182": "Border terrier",
        "183": "Kerry blue terrier",
        "184": "Irish terrier",
        "185": "Norfolk terrier",
        "186": "Norwich terrier",
        "187": "Yorkshire terrier",
        "188": "wire-haired fox terrier",
        "189": "Lakeland terrier",
        "190": "Sealyham terrier, Sealyham",
        "191": "Airedale, Airedale terrier",
        "192": "cairn, cairn terrier",
        "193": "Australian terrier",
        "194": "Dandie Dinmont, Dandie Dinmont terrier",
        "195": "Boston bull, Boston terrier",
        "196": "miniature schnauzer",
        "197": "giant schnauzer",
        "198": "standard schnauzer",
        "199": "Scotch terrier, Scottish terrier, Scottie",
        "200": "Tibetan terrier, chrysanthemum dog",
        "201": "silky terrier, Sydney silky",
        "202": "soft-coated wheaten terrier",
        "203": "West Highland white terrier",
        "204": "Lhasa, Lhasa apso",
        "205": "flat-coated retriever",
        "206": "curly-coated retriever",
        "207": "golden retriever",
        "208": "Labrador retriever",
        "209": "Chesapeake Bay retriever",
        "210": "German short-haired pointer",
        "211": "vizsla, Hungarian pointer",
        "212": "English setter",
        "213": "Irish setter, red setter",
        "214": "Gordon setter",
        "215": "Brittany spaniel",
        "216": "clumber, clumber spaniel",
        "217": "English springer, English springer spaniel",
        "218": "Welsh springer spaniel",
        "219": "cocker spaniel, English cocker spaniel, cocker",
        "220": "Sussex spaniel",
        "221": "Irish water spaniel",
        "222": "kuvasz",
        "223": "schipperke",
        "224": "groenendael",
        "225": "malinois",
        "226": "briard",
        "227": "kelpie",
        "228": "komondor",
        "229": "Old English sheepdog, bobtail",
        "230": "Shetland sheepdog, Shetland sheep dog, Shetland",
        "231": "collie",
        "232": "Border collie",
        "233": "Bouvier des Flandres, Bouviers des Flandres",
        "234": "Rottweiler",
        "235": "German shepherd, German shepherd dog, German police dog, alsatian",
        "236": "Doberman, Doberman pinscher",
        "237": "miniature pinscher",
        "238": "Greater Swiss Mountain dog",
        "239": "Bernese mountain dog",
        "240": "Appenzeller",
        "241": "EntleBucher",
        "242": "boxer",
        "243": "bull mastiff",
        "244": "Tibetan mastiff",
        "245": "French bulldog",
        "246": "Great Dane",
        "247": "Saint Bernard, St Bernard",
        "248": "Eskimo dog, husky",
        "249": "malamute, malemute, Alaskan malamute",
        "250": "Siberian husky",
        "251": "dalmatian, coach dog, carriage dog",
        "252": "affenpinscher, monkey pinscher, monkey dog",
        "253": "basenji",
        "254": "pug, pug-dog",
        "255": "Leonberg",
        "256": "Newfoundland, Newfoundland dog",
        "257": "Great Pyrenees",
        "258": "Samoyed, Samoyede",
        "259": "Pomeranian",
        "260": "chow, chow chow",
        "261": "keeshond",
        "262": "Brabancon griffon",
        "263": "Pembroke, Pembroke Welsh corgi",
        "264": "Cardigan, Cardigan Welsh corgi",
        "265": "toy poodle",
        "266": "miniature poodle",
        "267": "standard poodle",
        "268": "Mexican hairless",
        "269": "timber wolf, grey wolf, gray wolf, Canis lupus",
        "270": "white wolf, Arctic wolf, Canis lupus tundrarum",
        "271": "red wolf, maned wolf, Canis rufus, Canis niger",
        "272": "coyote, prairie wolf, brush wolf, Canis latrans",
        "273": "dingo, warrigal, warragal, Canis dingo",
        "274": "dhole, Cuon alpinus",
        "275": "African hunting dog, hyena dog, Cape hunting dog, Lycaon pictus",
        "276": "hyena, hyaena",
        "277": "red fox, Vulpes vulpes",
        "278": "kit fox, Vulpes macrotis",
        "279": "Arctic fox, white fox, Alopex lagopus",
        "280": "grey fox, gray fox, Urocyon cinereoargenteus",
        "281": "tabby, tabby cat",
        "282": "tiger cat",
        "283": "Persian cat",
        "284": "Siamese cat, Siamese",
        "285": "Egyptian cat",
        "286": "cougar, puma, catamount, mountain lion, painter, panther, Felis concolor",
        "287": "lynx, catamount",
        "288": "leopard, Panthera pardus",
        "289": "snow leopard, ounce, Panthera uncia",
        "290": "jaguar, panther, Panthera onca, Felis onca",
        "291": "lion, king of beasts, Panthera leo",
        "292": "tiger, Panthera tigris",
        "293": "cheetah, chetah, Acinonyx jubatus",
        "294": "brown bear, bruin, Ursus arctos",
        "295": "American black bear, black bear, Ursus americanus, Euarctos americanus",
        "296": "ice bear, polar bear, Ursus Maritimus, Thalarctos maritimus",
        "297": "sloth bear, Melursus ursinus, Ursus ursinus",
        "298": "mongoose",
        "299": "meerkat, mierkat",
        "300": "tiger beetle",
        "301": "ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle",
        "302": "ground beetle, carabid beetle",
        "303": "long-horned beetle, longicorn, longicorn beetle",
        "304": "leaf beetle, chrysomelid",
        "305": "dung beetle",
        "306": "rhinoceros beetle",
        "307": "weevil",
        "308": "fly",
        "309": "bee",
        "310": "ant, emmet, pismire",
        "311": "grasshopper, hopper",
        "312": "cricket",
        "313": "walking stick, walkingstick, stick insect",
        "314": "cockroach, roach",
        "315": "mantis, mantid",
        "316": "cicada, cicala",
        "317": "leafhopper",
        "318": "lacewing, lacewing fly",
        "319": "dragonfly, darning needle, devil's darning needle, sewing needle, snake feeder, snake doctor, mosquito hawk, skeeter hawk",
        "320": "damselfly",
        "321": "admiral",
        "322": "ringlet, ringlet butterfly",
        "323": "monarch, monarch butterfly, milkweed butterfly, Danaus plexippus",
        "324": "cabbage butterfly",
        "325": "sulphur butterfly, sulfur butterfly",
        "326": "lycaenid, lycaenid butterfly",
        "327": "starfish, sea star",
        "328": "sea urchin",
        "329": "sea cucumber, holothurian",
        "330": "wood rabbit, cottontail, cottontail rabbit",
        "331": "hare",
        "332": "Angora, Angora rabbit",
        "333": "hamster",
        "334": "porcupine, hedgehog",
        "335": "fox squirrel, eastern fox squirrel, Sciurus niger",
        "336": "marmot",
        "337": "beaver",
        "338": "guinea pig, Cavia cobaya",
        "339": "sorrel",
        "340": "zebra",
        "341": "hog, pig, grunter, squealer, Sus scrofa",
        "342": "wild boar, boar, Sus scrofa",
        "343": "warthog",
        "344": "hippopotamus, hippo, river horse, Hippopotamus amphibius",
        "345": "ox",
        "346": "water buffalo, water ox, Asiatic buffalo, Bubalus bubalis",
        "347": "bison",
        "348": "ram, tup",
        "349": "bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky Mountain sheep, Ovis canadensis",
        "350": "ibex, Capra ibex",
        "351": "hartebeest",
        "352": "impala, Aepyceros melampus",
        "353": "gazelle",
        "354": "Arabian camel, dromedary, Camelus dromedarius",
        "355": "llama",
        "356": "weasel",
        "357": "mink",
        "358": "polecat, fitch, foulmart, foumart, Mustela putorius",
        "359": "black-footed ferret, ferret, Mustela nigripes",
        "360": "otter",
        "361": "skunk, polecat, wood pussy",
        "362": "badger",
        "363": "armadillo",
        "364": "three-toed sloth, ai, Bradypus tridactylus",
        "365": "orangutan, orang, orangutang, Pongo pygmaeus",
        "366": "gorilla, Gorilla gorilla",
        "367": "chimpanzee, chimp, Pan troglodytes",
        "368": "gibbon, Hylobates lar",
        "369": "siamang, Hylobates syndactylus, Symphalangus syndactylus",
        "370": "guenon, guenon monkey",
        "371": "patas, hussar monkey, Erythrocebus patas",
        "372": "baboon",
        "373": "macaque",
        "374": "langur",
        "375": "colobus, colobus monkey",
        "376": "proboscis monkey, Nasalis larvatus",
        "377": "marmoset",
        "378": "capuchin, ringtail, Cebus capucinus",
        "379": "howler monkey, howler",
        "380": "titi, titi monkey",
        "381": "spider monkey, Ateles geoffroyi",
        "382": "squirrel monkey, Saimiri sciureus",
        "383": "Madagascar cat, ring-tailed lemur, Lemur catta",
        "384": "indri, indris, Indri indri, Indri brevicaudatus",
        "385": "Indian elephant, Elephas maximus",
        "386": "African elephant, Loxodonta africana",
        "387": "lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens",
        "388": "giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca",
        "389": "barracouta, snoek",
        "390": "eel",
        "391": "coho, cohoe, coho salmon, blue jack, silver salmon, Oncorhynchus kisutch",
        "392": "rock beauty, Holocanthus tricolor",
        "393": "anemone fish",
        "394": "sturgeon",
        "395": "gar, garfish, garpike, billfish, Lepisosteus osseus",
        "396": "lionfish",
        "397": "puffer, pufferfish, blowfish, globefish",
        "398": "abacus",
        "399": "abaya",
        "400": "academic gown, academic robe, judge's robe",
        "401": "accordion, piano accordion, squeeze box",
        "402": "acoustic guitar",
        "403": "aircraft carrier, carrier, flattop, attack aircraft carrier",
        "404": "airliner",
        "405": "airship, dirigible",
        "406": "altar",
        "407": "ambulance",
        "408": "amphibian, amphibious vehicle",
        "409": "analog clock",
        "410": "apiary, bee house",
        "411": "apron",
        "412": "ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustbin, trash barrel, trash bin",
        "413": "assault rifle, assault gun",
        "414": "backpack, back pack, knapsack, packsack, rucksack, haversack",
        "415": "bakery, bakeshop, bakehouse",
        "416": "balance beam, beam",
        "417": "balloon",
        "418": "ballpoint, ballpoint pen, ballpen, Biro",
        "419": "Band Aid",
        "420": "banjo",
        "421": "bannister, banister, balustrade, balusters, handrail",
        "422": "barbell",
        "423": "barber chair",
        "424": "barbershop",
        "425": "barn",
        "426": "barometer",
        "427": "barrel, cask",
        "428": "barrow, garden cart, lawn cart, wheelbarrow",
        "429": "baseball",
        "430": "basketball",
        "431": "bassinet",
        "432": "bassoon",
        "433": "bathing cap, swimming cap",
        "434": "bath towel",
        "435": "bathtub, bathing tub, bath, tub",
        "436": "beach wagon, station wagon, wagon, estate car, beach waggon, station waggon, waggon",
        "437": "beacon, lighthouse, beacon light, pharos",
        "438": "beaker",
        "439": "bearskin, busby, shako",
        "440": "beer bottle",
        "441": "beer glass",
        "442": "bell cote, bell cot",
        "443": "bib",
        "444": "bicycle-built-for-two, tandem bicycle, tandem",
        "445": "bikini, two-piece",
        "446": "binder, ring-binder",
        "447": "binoculars, field glasses, opera glasses",
        "448": "birdhouse",
        "449": "boathouse",
        "450": "bobsled, bobsleigh, bob",
        "451": "bolo tie, bolo, bola tie, bola",
        "452": "bonnet, poke bonnet",
        "453": "bookcase",
        "454": "bookshop, bookstore, bookstall",
        "455": "bottlecap",
        "456": "bow",
        "457": "bow tie, bow-tie, bowtie",
        "458": "brass, memorial tablet, plaque",
        "459": "brassiere, bra, bandeau",
        "460": "breakwater, groin, groyne, mole, bulwark, seawall, jetty",
        "461": "breastplate, aegis, egis",
        "462": "broom",
        "463": "bucket, pail",
        "464": "buckle",
        "465": "bulletproof vest",
        "466": "bullet train, bullet",
        "467": "butcher shop, meat market",
        "468": "cab, hack, taxi, taxicab",
        "469": "caldron, cauldron",
        "470": "candle, taper, wax light",
        "471": "cannon",
        "472": "canoe",
        "473": "can opener, tin opener",
        "474": "cardigan",
        "475": "car mirror",
        "476": "carousel, carrousel, merry-go-round, roundabout, whirligig",
        "477": "carpenter's kit, tool kit",
        "478": "carton",
        "479": "car wheel",
        "480": "cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM",
        "481": "cassette",
        "482": "cassette player",
        "483": "castle",
        "484": "catamaran",
        "485": "CD player",
        "486": "cello, violoncello",
        "487": "cellular telephone, cellular phone, cellphone, cell, mobile phone",
        "488": "chain",
        "489": "chainlink fence",
        "490": "chain mail, ring mail, mail, chain armor, chain armour, ring armor, ring armour",
        "491": "chain saw, chainsaw",
        "492": "chest",
        "493": "chiffonier, commode",
        "494": "chime, bell, gong",
        "495": "china cabinet, china closet",
        "496": "Christmas stocking",
        "497": "church, church building",
        "498": "cinema, movie theater, movie theatre, movie house, picture palace",
        "499": "cleaver, meat cleaver, chopper",
        "500": "cliff dwelling",
        "501": "cloak",
        "502": "clog, geta, patten, sabot",
        "503": "cocktail shaker",
        "504": "coffee mug",
        "505": "coffeepot",
        "506": "coil, spiral, volute, whorl, helix",
        "507": "combination lock",
        "508": "computer keyboard, keypad",
        "509": "confectionery, confectionary, candy store",
        "510": "container ship, containership, container vessel",
        "511": "convertible",
        "512": "corkscrew, bottle screw",
        "513": "cornet, horn, trumpet, trump",
        "514": "cowboy boot",
        "515": "cowboy hat, ten-gallon hat",
        "516": "cradle",
        "517": "crane2",
        "518": "crash helmet",
        "519": "crate",
        "520": "crib, cot",
        "521": "Crock Pot",
        "522": "croquet ball",
        "523": "crutch",
        "524": "cuirass",
        "525": "dam, dike, dyke",
        "526": "desk",
        "527": "desktop computer",
        "528": "dial telephone, dial phone",
        "529": "diaper, nappy, napkin",
        "530": "digital clock",
        "531": "digital watch",
        "532": "dining table, board",
        "533": "dishrag, dishcloth",
        "534": "dishwasher, dish washer, dishwashing machine",
        "535": "disk brake, disc brake",
        "536": "dock, dockage, docking facility",
        "537": "dogsled, dog sled, dog sleigh",
        "538": "dome",
        "539": "doormat, welcome mat",
        "540": "drilling platform, offshore rig",
        "541": "drum, membranophone, tympan",
        "542": "drumstick",
        "543": "dumbbell",
        "544": "Dutch oven",
        "545": "electric fan, blower",
        "546": "electric guitar",
        "547": "electric locomotive",
        "548": "entertainment center",
        "549": "envelope",
        "550": "espresso maker",
        "551": "face powder",
        "552": "feather boa, boa",
        "553": "file, file cabinet, filing cabinet",
        "554": "fireboat",
        "555": "fire engine, fire truck",
        "556": "fire screen, fireguard",
        "557": "flagpole, flagstaff",
        "558": "flute, transverse flute",
        "559": "folding chair",
        "560": "football helmet",
        "561": "forklift",
        "562": "fountain",
        "563": "fountain pen",
        "564": "four-poster",
        "565": "freight car",
        "566": "French horn, horn",
        "567": "frying pan, frypan, skillet",
        "568": "fur coat",
        "569": "garbage truck, dustcart",
        "570": "gasmask, respirator, gas helmet",
        "571": "gas pump, gasoline pump, petrol pump, island dispenser",
        "572": "goblet",
        "573": "go-kart",
        "574": "golf ball",
        "575": "golfcart, golf cart",
        "576": "gondola",
        "577": "gong, tam-tam",
        "578": "gown",
        "579": "grand piano, grand",
        "580": "greenhouse, nursery, glasshouse",
        "581": "grille, radiator grille",
        "582": "grocery store, grocery, food market, market",
        "583": "guillotine",
        "584": "hair slide",
        "585": "hair spray",
        "586": "half track",
        "587": "hammer",
        "588": "hamper",
        "589": "hand blower, blow dryer, blow drier, hair dryer, hair drier",
        "590": "hand-held computer, hand-held microcomputer",
        "591": "handkerchief, hankie, hanky, hankey",
        "592": "hard disc, hard disk, fixed disk",
        "593": "harmonica, mouth organ, harp, mouth harp",
        "594": "harp",
        "595": "harvester, reaper",
        "596": "hatchet",
        "597": "holster",
        "598": "home theater, home theatre",
        "599": "honeycomb",
        "600": "hook, claw",
        "601": "hoopskirt, crinoline",
        "602": "horizontal bar, high bar",
        "603": "horse cart, horse-cart",
        "604": "hourglass",
        "605": "iPod",
        "606": "iron, smoothing iron",
        "607": "jack-o'-lantern",
        "608": "jean, blue jean, denim",
        "609": "jeep, landrover",
        "610": "jersey, T-shirt, tee shirt",
        "611": "jigsaw puzzle",
        "612": "jinrikisha, ricksha, rickshaw",
        "613": "joystick",
        "614": "kimono",
        "615": "knee pad",
        "616": "knot",
        "617": "lab coat, laboratory coat",
        "618": "ladle",
        "619": "lampshade, lamp shade",
        "620": "laptop, laptop computer",
        "621": "lawn mower, mower",
        "622": "lens cap, lens cover",
        "623": "letter opener, paper knife, paperknife",
        "624": "library",
        "625": "lifeboat",
        "626": "lighter, light, igniter, ignitor",
        "627": "limousine, limo",
        "628": "liner, ocean liner",
        "629": "lipstick, lip rouge",
        "630": "Loafer",
        "631": "lotion",
        "632": "loudspeaker, speaker, speaker unit, loudspeaker system, speaker system",
        "633": "loupe, jeweler's loupe",
        "634": "lumbermill, sawmill",
        "635": "magnetic compass",
        "636": "mailbag, postbag",
        "637": "mailbox, letter box",
        "638": "maillot",
        "639": "maillot, tank suit",
        "640": "manhole cover",
        "641": "maraca",
        "642": "marimba, xylophone",
        "643": "mask",
        "644": "matchstick",
        "645": "maypole",
        "646": "maze, labyrinth",
        "647": "measuring cup",
        "648": "medicine chest, medicine cabinet",
        "649": "megalith, megalithic structure",
        "650": "microphone, mike",
        "651": "microwave, microwave oven",
        "652": "military uniform",
        "653": "milk can",
        "654": "minibus",
        "655": "miniskirt, mini",
        "656": "minivan",
        "657": "missile",
        "658": "mitten",
        "659": "mixing bowl",
        "660": "mobile home, manufactured home",
        "661": "Model T",
        "662": "modem",
        "663": "monastery",
        "664": "monitor",
        "665": "moped",
        "666": "mortar",
        "667": "mortarboard",
        "668": "mosque",
        "669": "mosquito net",
        "670": "motor scooter, scooter",
        "671": "mountain bike, all-terrain bike, off-roader",
        "672": "mountain tent",
        "673": "mouse, computer mouse",
        "674": "mousetrap",
        "675": "moving van",
        "676": "muzzle",
        "677": "nail",
        "678": "neck brace",
        "679": "necklace",
        "680": "nipple",
        "681": "notebook, notebook computer",
        "682": "obelisk",
        "683": "oboe, hautboy, hautbois",
        "684": "ocarina, sweet potato",
        "685": "odometer, hodometer, mileometer, milometer",
        "686": "oil filter",
        "687": "organ, pipe organ",
        "688": "oscilloscope, scope, cathode-ray oscilloscope, CRO",
        "689": "overskirt",
        "690": "oxcart",
        "691": "oxygen mask",
        "692": "packet",
        "693": "paddle, boat paddle",
        "694": "paddlewheel, paddle wheel",
        "695": "padlock",
        "696": "paintbrush",
        "697": "pajama, pyjama, pj's, jammies",
        "698": "palace",
        "699": "panpipe, pandean pipe, syrinx",
        "700": "paper towel",
        "701": "parachute, chute",
        "702": "parallel bars, bars",
        "703": "park bench",
        "704": "parking meter",
        "705": "passenger car, coach, carriage",
        "706": "patio, terrace",
        "707": "pay-phone, pay-station",
        "708": "pedestal, plinth, footstall",
        "709": "pencil box, pencil case",
        "710": "pencil sharpener",
        "711": "perfume, essence",
        "712": "Petri dish",
        "713": "photocopier",
        "714": "pick, plectrum, plectron",
        "715": "pickelhaube",
        "716": "picket fence, paling",
        "717": "pickup, pickup truck",
        "718": "pier",
        "719": "piggy bank, penny bank",
        "720": "pill bottle",
        "721": "pillow",
        "722": "ping-pong ball",
        "723": "pinwheel",
        "724": "pirate, pirate ship",
        "725": "pitcher, ewer",
        "726": "plane, carpenter's plane, woodworking plane",
        "727": "planetarium",
        "728": "plastic bag",
        "729": "plate rack",
        "730": "plow, plough",
        "731": "plunger, plumber's helper",
        "732": "Polaroid camera, Polaroid Land camera",
        "733": "pole",
        "734": "police van, police wagon, paddy wagon, patrol wagon, wagon, black Maria",
        "735": "poncho",
        "736": "pool table, billiard table, snooker table",
        "737": "pop bottle, soda bottle",
        "738": "pot, flowerpot",
        "739": "potter's wheel",
        "740": "power drill",
        "741": "prayer rug, prayer mat",
        "742": "printer",
        "743": "prison, prison house",
        "744": "projectile, missile",
        "745": "projector",
        "746": "puck, hockey puck",
        "747": "punching bag, punch bag, punching ball, punchball",
        "748": "purse",
        "749": "quill, quill pen",
        "750": "quilt, comforter, comfort, puff",
        "751": "racer, race car, racing car",
        "752": "racket, racquet",
        "753": "radiator",
        "754": "radio, wireless",
        "755": "radio telescope, radio reflector",
        "756": "rain barrel",
        "757": "recreational vehicle, RV, R.V.",
        "758": "reel",
        "759": "reflex camera",
        "760": "refrigerator, icebox",
        "761": "remote control, remote",
        "762": "restaurant, eating house, eating place, eatery",
        "763": "revolver, six-gun, six-shooter",
        "764": "rifle",
        "765": "rocking chair, rocker",
        "766": "rotisserie",
        "767": "rubber eraser, rubber, pencil eraser",
        "768": "rugby ball",
        "769": "rule, ruler",
        "770": "running shoe",
        "771": "safe",
        "772": "safety pin",
        "773": "saltshaker, salt shaker",
        "774": "sandal",
        "775": "sarong",
        "776": "sax, saxophone",
        "777": "scabbard",
        "778": "scale, weighing machine",
        "779": "school bus",
        "780": "schooner",
        "781": "scoreboard",
        "782": "screen, CRT screen",
        "783": "screw",
        "784": "screwdriver",
        "785": "seat belt, seatbelt",
        "786": "sewing machine",
        "787": "shield, buckler",
        "788": "shoe shop, shoe-shop, shoe store",
        "789": "shoji",
        "790": "shopping basket",
        "791": "shopping cart",
        "792": "shovel",
        "793": "shower cap",
        "794": "shower curtain",
        "795": "ski",
        "796": "ski mask",
        "797": "sleeping bag",
        "798": "slide rule, slipstick",
        "799": "sliding door",
        "800": "slot, one-armed bandit",
        "801": "snorkel",
        "802": "snowmobile",
        "803": "snowplow, snowplough",
        "804": "soap dispenser",
        "805": "soccer ball",
        "806": "sock",
        "807": "solar dish, solar collector, solar furnace",
        "808": "sombrero",
        "809": "soup bowl",
        "810": "space bar",
        "811": "space heater",
        "812": "space shuttle",
        "813": "spatula",
        "814": "speedboat",
        "815": "spider web, spider's web",
        "816": "spindle",
        "817": "sports car, sport car",
        "818": "spotlight, spot",
        "819": "stage",
        "820": "steam locomotive",
        "821": "steel arch bridge",
        "822": "steel drum",
        "823": "stethoscope",
        "824": "stole",
        "825": "stone wall",
        "826": "stopwatch, stop watch",
        "827": "stove",
        "828": "strainer",
        "829": "streetcar, tram, tramcar, trolley, trolley car",
        "830": "stretcher",
        "831": "studio couch, day bed",
        "832": "stupa, tope",
        "833": "submarine, pigboat, sub, U-boat",
        "834": "suit, suit of clothes",
        "835": "sundial",
        "836": "sunglass",
        "837": "sunglasses, dark glasses, shades",
        "838": "sunscreen, sunblock, sun blocker",
        "839": "suspension bridge",
        "840": "swab, swob, mop",
        "841": "sweatshirt",
        "842": "swimming trunks, bathing trunks",
        "843": "swing",
        "844": "switch, electric switch, electrical switch",
        "845": "syringe",
        "846": "table lamp",
        "847": "tank, army tank, armored combat vehicle, armoured combat vehicle",
        "848": "tape player",
        "849": "teapot",
        "850": "teddy, teddy bear",
        "851": "television, television system",
        "852": "tennis ball",
        "853": "thatch, thatched roof",
        "854": "theater curtain, theatre curtain",
        "855": "thimble",
        "856": "thresher, thrasher, threshing machine",
        "857": "throne",
        "858": "tile roof",
        "859": "toaster",
        "860": "tobacco shop, tobacconist shop, tobacconist",
        "861": "toilet seat",
        "862": "torch",
        "863": "totem pole",
        "864": "tow truck, tow car, wrecker",
        "865": "toyshop",
        "866": "tractor",
        "867": "trailer truck, tractor trailer, trucking rig, rig, articulated lorry, semi",
        "868": "tray",
        "869": "trench coat",
        "870": "tricycle, trike, velocipede",
        "871": "trimaran",
        "872": "tripod",
        "873": "triumphal arch",
        "874": "trolleybus, trolley coach, trackless trolley",
        "875": "trombone",
        "876": "tub, vat",
        "877": "turnstile",
        "878": "typewriter keyboard",
        "879": "umbrella",
        "880": "unicycle, monocycle",
        "881": "upright, upright piano",
        "882": "vacuum, vacuum cleaner",
        "883": "vase",
        "884": "vault",
        "885": "velvet",
        "886": "vending machine",
        "887": "vestment",
        "888": "viaduct",
        "889": "violin, fiddle",
        "890": "volleyball",
        "891": "waffle iron",
        "892": "wall clock",
        "893": "wallet, billfold, notecase, pocketbook",
        "894": "wardrobe, closet, press",
        "895": "warplane, military plane",
        "896": "washbasin, handbasin, washbowl, lavabo, wash-hand basin",
        "897": "washer, automatic washer, washing machine",
        "898": "water bottle",
        "899": "water jug",
        "900": "water tower",
        "901": "whiskey jug",
        "902": "whistle",
        "903": "wig",
        "904": "window screen",
        "905": "window shade",
        "906": "Windsor tie",
        "907": "wine bottle",
        "908": "wing",
        "909": "wok",
        "910": "wooden spoon",
        "911": "wool, woolen, woollen",
        "912": "worm fence, snake fence, snake-rail fence, Virginia fence",
        "913": "wreck",
        "914": "yawl",
        "915": "yurt",
        "916": "web site, website, internet site, site",
        "917": "comic book",
        "918": "crossword puzzle, crossword",
        "919": "street sign",
        "920": "traffic light, traffic signal, stoplight",
        "921": "book jacket, dust cover, dust jacket, dust wrapper",
        "922": "menu",
        "923": "plate",
        "924": "guacamole",
        "925": "consomme",
        "926": "hot pot, hotpot",
        "927": "trifle",
        "928": "ice cream, icecream",
        "929": "ice lolly, lolly, lollipop, popsicle",
        "930": "French loaf",
        "931": "bagel, beigel",
        "932": "pretzel",
        "933": "cheeseburger",
        "934": "hotdog, hot dog, red hot",
        "935": "mashed potato",
        "936": "head cabbage",
        "937": "broccoli",
        "938": "cauliflower",
        "939": "zucchini, courgette",
        "940": "spaghetti squash",
        "941": "acorn squash",
        "942": "butternut squash",
        "943": "cucumber, cuke",
        "944": "artichoke, globe artichoke",
        "945": "bell pepper",
        "946": "cardoon",
        "947": "mushroom",
        "948": "Granny Smith",
        "949": "strawberry",
        "950": "orange",
        "951": "lemon",
        "952": "fig",
        "953": "pineapple, ananas",
        "954": "banana",
        "955": "jackfruit, jak, jack",
        "956": "custard apple",
        "957": "pomegranate",
        "958": "hay",
        "959": "carbonara",
        "960": "chocolate sauce, chocolate syrup",
        "961": "dough",
        "962": "meat loaf, meatloaf",
        "963": "pizza, pizza pie",
        "964": "potpie",
        "965": "burrito",
        "966": "red wine",
        "967": "espresso",
        "968": "cup",
        "969": "eggnog",
        "970": "alp",
        "971": "bubble",
        "972": "cliff, drop, drop-off",
        "973": "coral reef",
        "974": "geyser",
        "975": "lakeside, lakeshore",
        "976": "promontory, headland, head, foreland",
        "977": "sandbar, sand bar",
        "978": "seashore, coast, seacoast, sea-coast",
        "979": "valley, vale",
        "980": "volcano",
        "981": "ballplayer, baseball player",
        "982": "groom, bridegroom",
        "983": "scuba diver",
        "984": "rapeseed",
        "985": "daisy",
        "986": "yellow lady's slipper, yellow lady-slipper, Cypripedium calceolus, Cypripedium parviflorum",
        "987": "corn",
        "988": "acorn",
        "989": "hip, rose hip, rosehip",
        "990": "buckeye, horse chestnut, conker",
        "991": "coral fungus",
        "992": "agaric",
        "993": "gyromitra",
        "994": "stinkhorn, carrion fungus",
        "995": "earthstar",
        "996": "hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa",
        "997": "bolete",
        "998": "ear, spike, capitulum",
        "999": "toilet tissue, toilet paper, bathroom tissue",
    }
)

IMAGENET_GENERIC_CLASSES = OrderedDict(
    {'0': 'teleost fish',
    '1': 'teleost fish',
    '2': 'cartilaginous fish',
    '3': 'cartilaginous fish',
    '4': 'fish',
    '5': 'fish',
    '6': 'fish',
    '7': 'animal',
    '8': 'animal',
    '9': 'chordate',
    '10': 'bird',
    '11': 'bird',
    '12': 'bird',
    '13': 'bird',
    '14': 'passerine',
    '15': 'bird',
    '16': 'passerine',
    '17': 'bird',
    '18': 'bird',
    '19': 'bird',
    '20': 'vertebrate',
    '21': 'vertebrate',
    '22': 'vertebrate',
    '23': 'chordate',
    '24': 'vertebrate',
    '25': 'chordate',
    '26': 'vertebrate',
    '27': 'vertebrate',
    '28': 'vertebrate',
    '29': 'vertebrate',
    '30': 'vertebrate',
    '31': 'chordate',
    '32': 'chordate',
    '33': 'anapsid',
    '34': 'anapsid',
    '35': 'reptile',
    '36': 'reptile',
    '37': 'reptile',
    '38': 'diapsid',
    '39': 'diapsid',
    '40': 'diapsid',
    '41': 'diapsid',
    '42': 'diapsid',
    '43': 'diapsid',
    '44': 'diapsid',
    '45': 'diapsid',
    '46': 'diapsid',
    '47': 'diapsid',
    '48': 'diapsid',
    '49': 'reptile',
    '50': 'reptile',
    '51': 'archosaur',
    '52': 'reptile',
    '53': 'reptile',
    '54': 'reptile',
    '55': 'reptile',
    '56': 'reptile',
    '57': 'reptile',
    '58': 'reptile',
    '59': 'reptile',
    '60': 'reptile',
    '61': 'diapsid',
    '62': 'snake',
    '63': 'diapsid',
    '64': 'snake',
    '65': 'vertebrate',
    '66': 'reptile',
    '67': 'snake',
    '68': 'snake',
    '69': 'organism',
    '70': 'animal',
    '71': 'animal',
    '72': 'invertebrate',
    '73': 'invertebrate',
    '74': 'invertebrate',
    '75': 'invertebrate',
    '76': 'invertebrate',
    '77': 'invertebrate',
    '78': 'invertebrate',
    '79': 'organism',
    '80': 'bird',
    '81': 'bird',
    '82': 'bird',
    '83': 'bird',
    '84': 'game bird',
    '85': 'bird',
    '86': 'bird',
    '87': 'chordate',
    '88': 'chordate',
    '89': 'vertebrate',
    '90': 'vertebrate',
    '91': 'vertebrate',
    '92': 'chordate',
    '93': 'chordate',
    '94': 'chordate',
    '95': 'chordate',
    '96': 'chordate',
    '97': 'aquatic bird',
    '98': 'anseriform bird',
    '99': 'bird',
    '100': 'vertebrate',
    '101': 'animal',
    '102': 'vertebrate',
    '103': 'vertebrate',
    '104': 'mammal',
    '105': 'mammal',
    '106': 'vertebrate',
    '107': 'organism',
    '108': 'animal',
    '109': 'coelenterate',
    '110': 'organism',
    '111': 'organism',
    '112': 'animal',
    '113': 'animal',
    '114': 'animal',
    '115': 'animal',
    '116': 'organism',
    '117': 'animal',
    '118': 'arthropod',
    '119': 'arthropod',
    '120': 'arthropod',
    '121': 'arthropod',
    '122': 'crustacean',
    '123': 'arthropod',
    '124': 'invertebrate',
    '125': 'invertebrate',
    '126': 'invertebrate',
    '127': 'bird',
    '128': 'bird',
    '129': 'vertebrate',
    '130': 'vertebrate',
    '131': 'bird',
    '132': 'aquatic bird',
    '133': 'bird',
    '134': 'vertebrate',
    '135': 'vertebrate',
    '136': 'bird',
    '137': 'aquatic bird',
    '138': 'vertebrate',
    '139': 'wading bird',
    '140': 'aquatic bird',
    '141': 'aquatic bird',
    '142': 'aquatic bird',
    '143': 'bird',
    '144': 'bird',
    '145': 'aquatic bird',
    '146': 'bird',
    '147': 'aquatic mammal',
    '148': 'cetacean',
    '149': 'mammal',
    '150': 'aquatic mammal',
    '151': 'carnivore',
    '152': 'carnivore',
    '153': 'carnivore',
    '154': 'carnivore',
    '155': 'carnivore',
    '156': 'dog',
    '157': 'canine',
    '158': 'carnivore',
    '159': 'carnivore',
    '160': 'canine',
    '161': 'canine',
    '162': 'canine',
    '163': 'canine',
    '164': 'canine',
    '165': 'dog',
    '166': 'dog',
    '167': 'dog',
    '168': 'canine',
    '169': 'dog',
    '170': 'dog',
    '171': 'dog',
    '172': 'dog',
    '173': 'canine',
    '174': 'canine',
    '175': 'canine',
    '176': 'canine',
    '177': 'canine',
    '178': 'canine',
    '179': 'dog',
    '180': 'dog',
    '181': 'canine',
    '182': 'canine',
    '183': 'canine',
    '184': 'canine',
    '185': 'canine',
    '186': 'canine',
    '187': 'canine',
    '188': 'dog',
    '189': 'dog',
    '190': 'hunting dog',
    '191': 'canine',
    '192': 'canine',
    '193': 'canine',
    '194': 'canine',
    '195': 'canine',
    '196': 'dog',
    '197': 'dog',
    '198': 'dog',
    '199': 'canine',
    '200': 'canine',
    '201': 'canine',
    '202': 'canine',
    '203': 'canine',
    '204': 'canine',
    '205': 'dog',
    '206': 'dog',
    '207': 'dog',
    '208': 'dog',
    '209': 'dog',
    '210': 'dog',
    '211': 'dog',
    '212': 'dog',
    '213': 'dog',
    '214': 'dog',
    '215': 'dog',
    '216': 'dog',
    '217': 'hunting dog',
    '218': 'hunting dog',
    '219': 'dog',
    '220': 'dog',
    '221': 'hunting dog',
    '222': 'canine',
    '223': 'canine',
    '224': 'dog',
    '225': 'dog',
    '226': 'canine',
    '227': 'canine',
    '228': 'canine',
    '229': 'canine',
    '230': 'canine',
    '231': 'canine',
    '232': 'canine',
    '233': 'canine',
    '234': 'canine',
    '235': 'canine',
    '236': 'dog',
    '237': 'dog',
    '238': 'canine',
    '239': 'canine',
    '240': 'canine',
    '241': 'canine',
    '242': 'carnivore',
    '243': 'carnivore',
    '244': 'canine',
    '245': 'canine',
    '246': 'carnivore',
    '247': 'carnivore',
    '248': 'carnivore',
    '249': 'canine',
    '250': 'canine',
    '251': 'placental',
    '252': 'dog',
    '253': 'placental',
    '254': 'placental',
    '255': 'placental',
    '256': 'placental',
    '257': 'placental',
    '258': 'carnivore',
    '259': 'carnivore',
    '260': 'carnivore',
    '261': 'carnivore',
    '262': 'carnivore',
    '263': 'carnivore',
    '264': 'carnivore',
    '265': 'carnivore',
    '266': 'carnivore',
    '267': 'carnivore',
    '268': 'placental',
    '269': 'placental',
    '270': 'placental',
    '271': 'placental',
    '272': 'placental',
    '273': 'placental',
    '274': 'placental',
    '275': 'placental',
    '276': 'mammal',
    '277': 'placental',
    '278': 'placental',
    '279': 'placental',
    '280': 'placental',
    '281': 'carnivore',
    '282': 'carnivore',
    '283': 'carnivore',
    '284': 'carnivore',
    '285': 'carnivore',
    '286': 'carnivore',
    '287': 'carnivore',
    '288': 'placental',
    '289': 'placental',
    '290': 'placental',
    '291': 'placental',
    '292': 'placental',
    '293': 'placental',
    '294': 'mammal',
    '295': 'mammal',
    '296': 'mammal',
    '297': 'mammal',
    '298': 'mammal',
    '299': 'mammal',
    '300': 'invertebrate',
    '301': 'invertebrate',
    '302': 'invertebrate',
    '303': 'invertebrate',
    '304': 'invertebrate',
    '305': 'insect',
    '306': 'insect',
    '307': 'invertebrate',
    '308': 'invertebrate',
    '309': 'invertebrate',
    '310': 'invertebrate',
    '311': 'invertebrate',
    '312': 'invertebrate',
    '313': 'invertebrate',
    '314': 'invertebrate',
    '315': 'invertebrate',
    '316': 'invertebrate',
    '317': 'invertebrate',
    '318': 'invertebrate',
    '319': 'invertebrate',
    '320': 'invertebrate',
    '321': 'insect',
    '322': 'arthropod',
    '323': 'insect',
    '324': 'insect',
    '325': 'arthropod',
    '326': 'arthropod',
    '327': 'organism',
    '328': 'organism',
    '329': 'organism',
    '330': 'placental',
    '331': 'mammal',
    '332': 'placental',
    '333': 'vertebrate',
    '334': 'vertebrate',
    '335': 'placental',
    '336': 'vertebrate',
    '337': 'vertebrate',
    '338': 'mammal',
    '339': 'ungulate',
    '340': 'placental',
    '341': 'placental',
    '342': 'placental',
    '343': 'placental',
    '344': 'mammal',
    '345': 'ruminant',
    '346': 'even-toed ungulate',
    '347': 'ungulate',
    '348': 'even-toed ungulate',
    '349': 'ruminant',
    '350': 'ruminant',
    '351': 'even-toed ungulate',
    '352': 'even-toed ungulate',
    '353': 'even-toed ungulate',
    '354': 'placental',
    '355': 'mammal',
    '356': 'mammal',
    '357': 'mammal',
    '358': 'mammal',
    '359': 'mammal',
    '360': 'mammal',
    '361': 'mammal',
    '362': 'mammal',
    '363': 'vertebrate',
    '364': 'mammal',
    '365': 'primate',
    '366': 'primate',
    '367': 'primate',
    '368': 'primate',
    '369': 'primate',
    '370': 'placental',
    '371': 'placental',
    '372': 'placental',
    '373': 'placental',
    '374': 'placental',
    '375': 'placental',
    '376': 'placental',
    '377': 'placental',
    '378': 'placental',
    '379': 'placental',
    '380': 'placental',
    '381': 'placental',
    '382': 'placental',
    '383': 'mammal',
    '384': 'mammal',
    '385': 'mammal',
    '386': 'mammal',
    '387': 'mammal',
    '388': 'mammal',
    '389': 'vertebrate',
    '390': 'fish',
    '391': 'aquatic vertebrate',
    '392': 'teleost fish',
    '393': 'teleost fish',
    '394': 'fish',
    '395': 'fish',
    '396': 'teleost fish',
    '397': 'bony fish',
    '398': 'instrumentality',
    '399': 'consumer goods',
    '400': 'consumer goods',
    '401': 'device',
    '402': 'device',
    '403': 'conveyance',
    '404': 'craft',
    '405': 'vehicle',
    '406': 'artifact',
    '407': 'wheeled vehicle',
    '408': 'vehicle',
    '409': 'instrument',
    '410': 'structure',
    '411': 'commodity',
    '412': 'artifact',
    '413': 'autoloader',
    '414': 'artifact',
    '415': 'establishment',
    '416': 'instrumentality',
    '417': 'vehicle',
    '418': 'instrumentality',
    '419': 'cloth covering',
    '420': 'instrumentality',
    '421': 'artifact',
    '422': 'instrumentality',
    '423': 'furnishing',
    '424': 'establishment',
    '425': 'artifact',
    '426': 'instrumentality',
    '427': 'artifact',
    '428': 'conveyance',
    '429': 'instrumentality',
    '430': 'instrumentality',
    '431': 'instrumentality',
    '432': 'wind instrument',
    '433': 'consumer goods',
    '434': 'drygoods',
    '435': 'artifact',
    '436': 'wheeled vehicle',
    '437': 'artifact',
    '438': 'instrumentality',
    '439': 'consumer goods',
    '440': 'instrumentality',
    '441': 'artifact',
    '442': 'artifact',
    '443': 'artifact',
    '444': 'conveyance',
    '445': 'consumer goods',
    '446': 'artifact',
    '447': 'instrumentality',
    '448': 'artifact',
    '449': 'structure',
    '450': 'instrumentality',
    '451': 'clothing',
    '452': 'consumer goods',
    '453': 'artifact',
    '454': 'establishment',
    '455': 'artifact',
    '456': 'instrumentality',
    '457': 'clothing',
    '458': 'artifact',
    '459': 'commodity',
    '460': 'artifact',
    '461': 'protective covering',
    '462': 'artifact',
    '463': 'artifact',
    '464': 'instrumentality',
    '465': 'consumer goods',
    '466': 'conveyance',
    '467': 'establishment',
    '468': 'wheeled vehicle',
    '469': 'instrumentality',
    '470': 'instrumentality',
    '471': 'device',
    '472': 'craft',
    '473': 'implement',
    '474': 'consumer goods',
    '475': 'instrumentality',
    '476': 'device',
    '477': 'instrumentality',
    '478': 'artifact',
    '479': 'mechanism',
    '480': 'artifact',
    '481': 'artifact',
    '482': 'artifact',
    '483': 'artifact',
    '484': 'craft',
    '485': 'artifact',
    '486': 'device',
    '487': 'equipment',
    '488': 'instrumentality',
    '489': 'structure',
    '490': 'covering',
    '491': 'implement',
    '492': 'artifact',
    '493': 'instrumentality',
    '494': 'instrumentality',
    '495': 'instrumentality',
    '496': 'clothing',
    '497': 'artifact',
    '498': 'artifact',
    '499': 'cutting implement',
    '500': 'artifact',
    '501': 'consumer goods',
    '502': 'artifact',
    '503': 'artifact',
    '504': 'container',
    '505': 'instrumentality',
    '506': 'artifact',
    '507': 'device',
    '508': 'equipment',
    '509': 'establishment',
    '510': 'craft',
    '511': 'wheeled vehicle',
    '512': 'tool',
    '513': 'device',
    '514': 'artifact',
    '515': 'consumer goods',
    '516': 'instrumentality',
    '517': 'artifact',
    '518': 'consumer goods',
    '519': 'artifact',
    '520': 'instrumentality',
    '521': 'utensil',
    '522': 'instrumentality',
    '523': 'instrumentality',
    '524': 'covering',
    '525': 'artifact',
    '526': 'instrumentality',
    '527': 'machine',
    '528': 'instrumentality',
    '529': 'commodity',
    '530': 'instrument',
    '531': 'instrument',
    '532': 'instrumentality',
    '533': 'artifact',
    '534': 'durables',
    '535': 'restraint',
    '536': 'artifact',
    '537': 'instrumentality',
    '538': 'artifact',
    '539': 'artifact',
    '540': 'equipment',
    '541': 'instrumentality',
    '542': 'artifact',
    '543': 'instrumentality',
    '544': 'appliance',
    '545': 'artifact',
    '546': 'device',
    '547': 'vehicle',
    '548': 'instrumentality',
    '549': 'artifact',
    '550': 'appliance',
    '551': 'instrumentality',
    '552': 'consumer goods',
    '553': 'instrumentality',
    '554': 'vehicle',
    '555': 'wheeled vehicle',
    '556': 'artifact',
    '557': 'instrumentality',
    '558': 'device',
    '559': 'furnishing',
    '560': 'consumer goods',
    '561': 'conveyance',
    '562': 'artifact',
    '563': 'instrumentality',
    '564': 'furnishing',
    '565': 'conveyance',
    '566': 'device',
    '567': 'utensil',
    '568': 'clothing',
    '569': 'wheeled vehicle',
    '570': 'artifact',
    '571': 'device',
    '572': 'artifact',
    '573': 'vehicle',
    '574': 'instrumentality',
    '575': 'vehicle',
    '576': 'vehicle',
    '577': 'instrumentality',
    '578': 'consumer goods',
    '579': 'device',
    '580': 'artifact',
    '581': 'structure',
    '582': 'establishment',
    '583': 'instrumentality',
    '584': 'device',
    '585': 'artifact',
    '586': 'vehicle',
    '587': 'instrumentality',
    '588': 'artifact',
    '589': 'consumer goods',
    '590': 'computer',
    '591': 'artifact',
    '592': 'instrumentality',
    '593': 'device',
    '594': 'device',
    '595': 'instrumentality',
    '596': 'cutting implement',
    '597': 'artifact',
    '598': 'artifact',
    '599': 'artifact',
    '600': 'instrumentality',
    '601': 'consumer goods',
    '602': 'instrumentality',
    '603': 'vehicle',
    '604': 'instrument',
    '605': 'system',
    '606': 'consumer goods',
    '607': 'device',
    '608': 'consumer goods',
    '609': 'wheeled vehicle',
    '610': 'consumer goods',
    '611': 'equipment',
    '612': 'vehicle',
    '613': 'equipment',
    '614': 'consumer goods',
    '615': 'commodity',
    '616': 'instrumentality',
    '617': 'clothing',
    '618': 'artifact',
    '619': 'artifact',
    '620': 'computer',
    '621': 'instrumentality',
    '622': 'artifact',
    '623': 'cutting implement',
    '624': 'artifact',
    '625': 'craft',
    '626': 'artifact',
    '627': 'wheeled vehicle',
    '628': 'craft',
    '629': 'instrumentality',
    '630': 'artifact',
    '631': 'artifact',
    '632': 'device',
    '633': 'magnifier',
    '634': 'structure',
    '635': 'device',
    '636': 'artifact',
    '637': 'artifact',
    '638': 'clothing',
    '639': 'consumer goods',
    '640': 'artifact',
    '641': 'instrumentality',
    '642': 'instrumentality',
    '643': 'consumer goods',
    '644': 'artifact',
    '645': 'support',
    '646': 'artifact',
    '647': 'artifact',
    '648': 'instrumentality',
    '649': 'artifact',
    '650': 'device',
    '651': 'durables',
    '652': 'commodity',
    '653': 'artifact',
    '654': 'instrumentality',
    '655': 'consumer goods',
    '656': 'motor vehicle',
    '657': 'instrumentality',
    '658': 'consumer goods',
    '659': 'tableware',
    '660': 'artifact',
    '661': 'wheeled vehicle',
    '662': 'artifact',
    '663': 'dwelling',
    '664': 'artifact',
    '665': 'self-propelled vehicle',
    '666': 'artifact',
    '667': 'consumer goods',
    '668': 'artifact',
    '669': 'artifact',
    '670': 'instrumentality',
    '671': 'conveyance',
    '672': 'artifact',
    '673': 'artifact',
    '674': 'artifact',
    '675': 'self-propelled vehicle',
    '676': 'artifact',
    '677': 'instrumentality',
    '678': 'instrumentality',
    '679': 'artifact',
    '680': 'artifact',
    '681': 'computer',
    '682': 'artifact',
    '683': 'wind instrument',
    '684': 'instrumentality',
    '685': 'device',
    '686': 'artifact',
    '687': 'instrumentality',
    '688': 'artifact',
    '689': 'consumer goods',
    '690': 'vehicle',
    '691': 'artifact',
    '692': 'artifact',
    '693': 'artifact',
    '694': 'mechanism',
    '695': 'device',
    '696': 'artifact',
    '697': 'commodity',
    '698': 'housing',
    '699': 'device',
    '700': 'artifact',
    '701': 'artifact',
    '702': 'instrumentality',
    '703': 'furnishing',
    '704': 'instrument',
    '705': 'conveyance',
    '706': 'artifact',
    '707': 'instrumentality',
    '708': 'artifact',
    '709': 'artifact',
    '710': 'artifact',
    '711': 'artifact',
    '712': 'ware',
    '713': 'instrumentality',
    '714': 'artifact',
    '715': 'shield',
    '716': 'structure',
    '717': 'wheeled vehicle',
    '718': 'artifact',
    '719': 'artifact',
    '720': 'instrumentality',
    '721': 'artifact',
    '722': 'instrumentality',
    '723': 'mechanism',
    '724': 'vehicle',
    '725': 'artifact',
    '726': 'instrumentality',
    '727': 'artifact',
    '728': 'artifact',
    '729': 'structure',
    '730': 'artifact',
    '731': 'instrumentality',
    '732': 'instrumentality',
    '733': 'artifact',
    '734': 'self-propelled vehicle',
    '735': 'clothing',
    '736': 'instrumentality',
    '737': 'instrumentality',
    '738': 'artifact',
    '739': 'mechanism',
    '740': 'instrumentality',
    '741': 'artifact',
    '742': 'instrumentality',
    '743': 'establishment',
    '744': 'instrumentality',
    '745': 'instrumentality',
    '746': 'artifact',
    '747': 'instrumentality',
    '748': 'artifact',
    '749': 'instrumentality',
    '750': 'artifact',
    '751': 'wheeled vehicle',
    '752': 'artifact',
    '753': 'artifact',
    '754': 'artifact',
    '755': 'scientific instrument',
    '756': 'artifact',
    '757': 'conveyance',
    '758': 'device',
    '759': 'instrumentality',
    '760': 'durables',
    '761': 'artifact',
    '762': 'artifact',
    '763': 'weapon',
    '764': 'instrument',
    '765': 'furnishing',
    '766': 'appliance',
    '767': 'artifact',
    '768': 'instrumentality',
    '769': 'device',
    '770': 'artifact',
    '771': 'instrumentality',
    '772': 'device',
    '773': 'artifact',
    '774': 'artifact',
    '775': 'consumer goods',
    '776': 'wind instrument',
    '777': 'artifact',
    '778': 'instrumentality',
    '779': 'instrumentality',
    '780': 'vehicle',
    '781': 'artifact',
    '782': 'instrumentality',
    '783': 'instrumentality',
    '784': 'instrumentality',
    '785': 'clothing',
    '786': 'consumer goods',
    '787': 'artifact',
    '788': 'establishment',
    '789': 'artifact',
    '790': 'artifact',
    '791': 'conveyance',
    '792': 'instrumentality',
    '793': 'consumer goods',
    '794': 'covering',
    '795': 'artifact',
    '796': 'covering',
    '797': 'artifact',
    '798': 'device',
    '799': 'obstruction',
    '800': 'instrumentality',
    '801': 'artifact',
    '802': 'vehicle',
    '803': 'vehicle',
    '804': 'artifact',
    '805': 'instrumentality',
    '806': 'consumer goods',
    '807': 'artifact',
    '808': 'consumer goods',
    '809': 'tableware',
    '810': 'implement',
    '811': 'artifact',
    '812': 'conveyance',
    '813': 'utensil',
    '814': 'craft',
    '815': 'instrumentality',
    '816': 'artifact',
    '817': 'wheeled vehicle',
    '818': 'instrumentality',
    '819': 'artifact',
    '820': 'vehicle',
    '821': 'artifact',
    '822': 'instrumentality',
    '823': 'instrumentality',
    '824': 'consumer goods',
    '825': 'structure',
    '826': 'instrument',
    '827': 'artifact',
    '828': 'artifact',
    '829': 'conveyance',
    '830': 'artifact',
    '831': 'furniture',
    '832': 'structure',
    '833': 'vehicle',
    '834': 'commodity',
    '835': 'device',
    '836': 'device',
    '837': 'device',
    '838': 'artifact',
    '839': 'artifact',
    '840': 'artifact',
    '841': 'clothing',
    '842': 'consumer goods',
    '843': 'artifact',
    '844': 'instrumentality',
    '845': 'instrumentality',
    '846': 'instrumentality',
    '847': 'vehicle',
    '848': 'artifact',
    '849': 'instrumentality',
    '850': 'artifact',
    '851': 'instrumentality',
    '852': 'instrumentality',
    '853': 'artifact',
    '854': 'covering',
    '855': 'artifact',
    '856': 'instrumentality',
    '857': 'furniture',
    '858': 'artifact',
    '859': 'durables',
    '860': 'establishment',
    '861': 'instrumentality',
    '862': 'instrumentality',
    '863': 'artifact',
    '864': 'wheeled vehicle',
    '865': 'establishment',
    '866': 'conveyance',
    '867': 'wheeled vehicle',
    '868': 'artifact',
    '869': 'garment',
    '870': 'instrumentality',
    '871': 'craft',
    '872': 'instrumentality',
    '873': 'artifact',
    '874': 'instrumentality',
    '875': 'device',
    '876': 'artifact',
    '877': 'obstruction',
    '878': 'artifact',
    '879': 'covering',
    '880': 'instrumentality',
    '881': 'device',
    '882': 'consumer goods',
    '883': 'instrumentality',
    '884': 'artifact',
    '885': 'artifact',
    '886': 'instrumentality',
    '887': 'consumer goods',
    '888': 'artifact',
    '889': 'device',
    '890': 'instrumentality',
    '891': 'durables',
    '892': 'instrument',
    '893': 'artifact',
    '894': 'artifact',
    '895': 'instrumentality',
    '896': 'instrumentality',
    '897': 'durables',
    '898': 'instrumentality',
    '899': 'container',
    '900': 'container',
    '901': 'container',
    '902': 'artifact',
    '903': 'consumer goods',
    '904': 'artifact',
    '905': 'covering',
    '906': 'clothing',
    '907': 'instrumentality',
    '908': 'artifact',
    '909': 'utensil',
    '910': 'ware',
    '911': 'artifact',
    '912': 'obstruction',
    '913': 'vehicle',
    '914': 'craft',
    '915': 'artifact',
    '916': 'instrumentality',
    '917': 'product',
    '918': 'equipment',
    '919': 'street sign',
    '920': 'traffic light',
    '921': 'artifact',
    '922': 'menu',
    '923': 'artifact',
    '924': 'dip',
    '925': 'nutriment',
    '926': 'nutriment',
    '927': 'nutriment',
    '928': 'nutriment',
    '929': 'nutriment',
    '930': 'french loaf',
    '931': 'bun',
    '932': 'pretzel',
    '933': 'sandwich',
    '934': 'sandwich',
    '935': 'vegetable',
    '936': 'vegetable',
    '937': 'vegetable',
    '938': 'vegetable',
    '939': 'vegetable',
    '940': 'vegetable',
    '941': 'vegetable',
    '942': 'vegetable',
    '943': 'vegetable',
    '944': 'vegetable',
    '945': 'vegetable',
    '946': 'vegetable',
    '947': 'vegetable',
    '948': 'fruit',
    '949': 'plant reproductive structure',
    '950': 'plant reproductive structure',
    '951': 'plant reproductive structure',
    '952': 'plant organ',
    '953': 'plant organ',
    '954': 'plant organ',
    '955': 'plant organ',
    '956': 'plant organ',
    '957': 'plant organ',
    '958': 'feed',
    '959': 'carbonara',
    '960': 'sauce',
    '961': 'foodstuff',
    '962': 'nutriment',
    '963': 'nutriment',
    '964': 'nutriment',
    '965': 'nutriment',
    '966': 'beverage',
    '967': 'beverage',
    '968': 'beverage',
    '969': 'beverage',
    '970': 'geological formation',
    '971': 'bubble',
    '972': 'geological formation',
    '973': 'geological formation',
    '974': 'geological formation',
    '975': 'geological formation',
    '976': 'geological formation',
    '977': 'natural object',
    '978': 'geological formation',
    '979': 'geological formation',
    '980': 'geological formation',
    '981': 'organism',
    '982': 'person',
    '983': 'organism',
    '984': 'plant reproductive structure',
    '985': 'vascular plant',
    '986': 'angiosperm',
    '987': 'fruit',
    '988': 'plant part',
    '989': 'plant part',
    '990': 'plant organ',
    '991': 'organism',
    '992': 'organism',
    '993': 'organism',
    '994': 'organism',
    '995': 'organism',
    '996': 'organism',
    '997': 'organism',
    '998': 'plant part',
    '999': 'toilet tissue'}
)