from collections import OrderedDict
MEDMNIST_CLASSES = OrderedDict(
    {     
	    "0": "adipose colon pathology imaging",
        "1": "background colon pathology imaging",
        "2": "debris colon pathology imaging",
        "3": "lymphocytes colon pathology imaging",
        "4": "mucus colon pathology imaging",
        "5": "smooth muscle colon pathology imaging",
        "6": "normal colon mucosa colon pathology imaging",
        "7": "cancer-associated stroma colon pathology imaging",
        "8": "colorectal adenocarcinoma epithelium colon pathology imaging",
        "9": "basophil blood cell microscope imaging",
        "10": "eosinophil blood cell microscope imaging",
        "11": "erythroblast blood cell microscope imaging",
        "12": "immature granulocytes (myelocytes, metamyelocytes and promyelocytes) blood cell microscope imaging",
        "13": "lymphocyte blood cell microscope imaging",
        "14": "monocyte blood cell microscope imaging",
        "15": "neutrophil blood cell microscope imaging",
        "16": "platelet blood cell microscope imaging",
        "17": "Collecting Duct, Connecting Tubule kidney cortex microscope imaging",
        "18": "Distal Convoluted Tubule kidney cortex microscope imaging",
        "19": "Glomerular endothelial cells kidney cortex microscope imaging",
        "20": "Interstitial endothelial cells kidney cortex microscope imaging",
        "21": "Leukocytes kidney cortex microscope imaging",
        "22": "Podocytes kidney cortex microscope imaging",
        "23": "Proximal Tubule Segments kidney cortex microscope imaging",
        "24": "Thick Ascending Limb kidney cortex microscope imaging",
    }
)

MEDMNIST_GENERIC_CLASSES = OrderedDict(
    {     
	    "0": "pathology image",
        "1": "pathology image",
        "2": "pathology image",
        "3": "pathology image",
        "4": "pathology image",
        "5": "pathology image",
        "6": "pathology image",
        "7": "pathology image",
        "8": "pathology image",
        "9": "microscopy image",
        "10": "microscopy image",
        "11": "microscopy image",
        "12": "microscopy image",
        "13": "microscopy image",
        "14": "microscopy image",
        "15": "microscopy image",
        "16": "microscopy image",
        "17": "microscope imaging",
        "18": "microscope imaging",
        "19": "microscope imaging",
        "20": "microscope imaging",
        "21": "microscope imaging",
        "22": "microscope imaging",
        "23": "microscope imaging",
        "24": "microscope imaging",
    }
)