from collections import OrderedDict
PETS_CLASSES = OrderedDict(
    {     
	    "0": "Abyssinian",
        "1": "American Bulldog",
        "2": "American Pit Bull Terrier",
        "3": "Basset Hound",
        "4": "Beagle",
        "5": "Bengal",
        "6": "Birman",
        "7": "Bombay",
        "8": "Boxer",
        "9": "British Shorthair",
        "10": "Chihuahua",
        "11": "Egyptian Mau",
        "12": "English Cocker Spaniel",
        "13": "English Setter",
        "14": "German Shorthaired",
        "15": "Great Pyrenees",
        "16": "Havanese",
        "17": "Japanese Chin",
        "18": "Keeshond",
        "19": "Leonberger",
        "20": "Maine Coon",
        "21": "Miniature Pinscher",
        "22": "New Found Land",
        "23": "Persian",
        "24": "Pomeranian",
        "25": "Pug",
        "26": "Ragdoll",
        "27": "Russian Blue",
        "28": "Saint Bernard",
        "29": "Samoyed",
        "30": "Scottish Terrier",
        "31": "Shiba Inu",
        "32": "Siamese",
        "33": "Sphynx",
        "34": "Staffordshire Bull Terrier",
        "35": "Wheaten Terrier",
        "36": "Yorkshire Terrier",
    }
)

PETS_GENERIC_CLASSES = OrderedDict(
    {     
	    "0": "Cat",
        "1": "Dog",
        "2": "Dog",
        "3": "Dog",
        "4": "Dog",
        "5": "Cat",
        "6": "Cat",
        "7": "Cat",
        "8": "Dog",
        "9": "Cat",
        "10": "Dog",
        "11": "Cat",
        "12": "Dog",
        "13": "Dog",
        "14": "Dog",
        "15": "Dog",
        "16": "Dog",
        "17": "Dog",
        "18": "Dog",
        "19": "Dog",
        "20": "Cat",
        "21": "Dog",
        "22": "Dog",
        "23": "Cat",
        "24": "Dog",
        "25": "Dog",
        "26": "Cat",
        "27": "Cat",
        "28": "Dog",
        "29": "Dog",
        "30": "Dog",
        "31": "Dog",
        "32": "Cat",
        "33": "Cat",
        "34": "Dog",
        "35": "Dog",
        "36": "Dog",
    }
)